# Generated by Django 4.1.1 on 2022-09-26 07:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, choices=[('PHILIPS', 'philips'), ('TCL', 'tcl'), ('Botech', 'botech'), ('ARÇELİK', 'arcelik'), ('VESTEL', 'vestel'), ('BEKO', 'beko'), ('CVS', 'cvs'), ('Dreamstar', 'dreamstar'), ('TECHNOBOX', 'technobox')], max_length=50, null=True)),
                ('durum', models.CharField(blank=True, choices=[('0', '0'), ('2.El', '2')], max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'product gallery',
            },
        ),
    ]
