# Generated by Django 4.1.7 on 2023-02-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Lifemaxx', 'lifemaxx'), ('INNOLUX', 'innolux'), ('REGAL', 'regal'), ('DARFON', 'darfon'), ('-', ''), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('YUMATU', 'yumatu'), ('Vestel-Regal', 'vestel-regal'), ('CHIMEI', 'chimei'), ('AXEN', 'axen'), ('Vestel', 'vestel'), ('Panasonic', 'panasonic'), ('Navitech', 'navitech'), ('Osawa', 'osawa'), ('ONVO', 'onvo'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('SAMSUNG', 'samsung'), ('Next', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('PHILIPS', 'philips'), ('SEG', 'seg'), ('SUNNY', 'sunny'), ('SHARP', 'sharp'), ('MEGMEET', 'megmeet'), ('Nordmende', 'nordmende'), ('Acer', 'acer'), ('Profilo', 'profilo'), ('NEXT', 'next'), ('Premier', 'premier'), ('Hisense', 'hisense'), ('WOON', 'woon'), ('Dreamstar', 'dreamstar'), ('RONAX-TELENOVA', 'ronax-telenova'), ('BOE', 'boe'), ('AUO', 'auo'), ('Vestel-SEG', 'vestel-seg'), ('LG', 'lg'), ('SUNNY-AXEN', 'sunny-axen'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Hi-Level', 'hi-level'), ('GEEPAS', 'geepas'), ('Vestel-ALBA', 'vestel-alba'), ('ROWELL', 'rowell'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('SONY', 'sony'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Homstar', 'homstar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED', 'led'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
