# Generated by Django 4.1.1 on 2022-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('AWOX', 'awox'), ('Profilo', 'profilo'), ('TELENOVA', 'telenova'), ('Botech', 'botech'), ('SANYO', 'sanyo'), ('Dreamstar', 'dreamstar'), ('VESTEL', 'vestel'), ('BEKO', 'beko'), ('ARÇELİK', 'arcelik'), ('TCL', 'tcl'), ('SAMSUNG', 'samsung'), ('CVS', 'cvs'), ('PHILIPS', 'philips'), ('LG', 'lg'), ('NEXT', 'next'), ('Dijitsu', 'dijitsu'), ('SUNNY', 'sunny'), ('TECHNOBOX', 'technobox')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.El', '2'), ('0', '0')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
