# Generated by Django 4.1.7 on 2023-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel-Regal', 'vestel-regal'), ('PHILIPS', 'philips'), ('Nordmende', 'nordmende'), ('YUMATU', 'yumatu'), ('ROWELL', 'rowell'), ('-', ''), ('Lifemaxx', 'lifemaxx'), ('INNOLUX', 'innolux'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Hi-Level', 'hi-level'), ('ONVO', 'onvo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('DARFON', 'darfon'), ('Osawa', 'osawa'), ('BOE', 'boe'), ('WOON', 'woon'), ('Dreamstar', 'dreamstar'), ('Acer', 'acer'), ('Profilo', 'profilo'), ('SEG', 'seg'), ('Vestel-SEG', 'vestel-seg'), ('GEEPAS', 'geepas'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('CHIMEI', 'chimei'), ('SHARP', 'sharp'), ('Hisense', 'hisense'), ('Skytech', 'skytech'), ('Premier', 'premier'), ('SAMSUNG', 'samsung'), ('AXEN', 'axen'), ('AUO', 'auo'), ('Panasonic', 'panasonic'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SONY', 'sony'), ('REGAL', 'regal'), ('SANYO', 'sanyo'), ('Vestel', 'vestel'), ('MEGMEET', 'megmeet'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel-ALBA', 'vestel-alba'), ('SUNNY', 'sunny'), ('NEXT', 'next'), ('Homstar', 'homstar'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Next', 'next'), ('LG', 'lg'), ('Dijitsu', 'dijitsu'), ('Navitech', 'navitech'), ('AWOX', 'awox')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
