# Generated by Django 4.1.1 on 2022-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Profilo', 'profilo'), ('BEKO', 'beko'), ('LG', 'lg'), ('TECHNOBOX', 'technobox'), ('CVS', 'cvs'), ('SANYO', 'sanyo'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('TCL', 'tcl'), ('Botech', 'botech'), ('PHILIPS', 'philips'), ('SAMSUNG', 'samsung'), ('VESTEL', 'vestel'), ('ARÇELİK', 'arcelik'), ('TELENOVA', 'telenova'), ('Dreamstar', 'dreamstar')], max_length=50, null=True),
        ),
    ]
