# Generated by Django 4.1.7 on 2023-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('AUO', 'auo'), ('-', ''), ('BOE', 'boe'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('Profilo', 'profilo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dreamstar', 'dreamstar'), ('CHIMEI', 'chimei'), ('Hisense', 'hisense'), ('SEG', 'seg'), ('ROWELL', 'rowell'), ('Lifemaxx', 'lifemaxx'), ('Vestel-ALBA', 'vestel-alba'), ('Nordmende', 'nordmende'), ('LG', 'lg'), ('Dijitsu', 'dijitsu'), ('PHILIPS', 'philips'), ('REGAL', 'regal'), ('Vestel-Regal', 'vestel-regal'), ('Osawa', 'osawa'), ('Next', 'next'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('SANYO', 'sanyo'), ('SONY', 'sony'), ('Acer', 'acer'), ('DARFON', 'darfon'), ('SHARP', 'sharp'), ('AXEN', 'axen'), ('Panasonic', 'panasonic'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Premier', 'premier'), ('SUNNY-AXEN', 'sunny-axen'), ('SUNNY', 'sunny'), ('YUMATU', 'yumatu'), ('Vestel', 'vestel'), ('NEXT', 'next'), ('Homstar', 'homstar'), ('Vestel-SEG', 'vestel-seg'), ('MEGMEET', 'megmeet'), ('Skytech', 'skytech'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Navitech', 'navitech'), ('INNOLUX', 'innolux'), ('ONVO', 'onvo'), ('WOON', 'woon'), ('AWOX', 'awox'), ('SAMSUNG', 'samsung')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
