# Generated by Django 4.1.7 on 2023-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SONY', 'sony'), ('Hisense', 'hisense'), ('SHARP', 'sharp'), ('AWOX', 'awox'), ('INNOLUX', 'innolux'), ('Vestel', 'vestel'), ('Next', 'next'), ('Nordmende', 'nordmende'), ('Dreamstar', 'dreamstar'), ('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Skytech', 'skytech'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('CHIMEI', 'chimei'), ('SAMSUNG', 'samsung'), ('AUO', 'auo'), ('SUNNY-AXEN', 'sunny-axen'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('REGAL', 'regal'), ('-', ''), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('PHILIPS', 'philips'), ('Acer', 'acer'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AXEN', 'axen'), ('Vestel-ALBA', 'vestel-alba'), ('SEG', 'seg'), ('MEGMEET', 'megmeet'), ('Profilo', 'profilo'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('DARFON', 'darfon'), ('Vestel-Regal', 'vestel-regal'), ('Panasonic', 'panasonic'), ('Osawa', 'osawa'), ('BOE', 'boe'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('GEEPAS', 'geepas'), ('Navitech', 'navitech'), ('Lifemaxx', 'lifemaxx'), ('Hi-Level', 'hi-level'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Premier', 'premier'), ('Homstar', 'homstar'), ('LG', 'lg'), ('WOON', 'woon'), ('YUMATU', 'yumatu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
