# Generated by Django 4.1.7 on 2023-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('INNOLUX', 'innolux'), ('SANYO', 'sanyo'), ('AXEN', 'axen'), ('Nordmende', 'nordmende'), ('CHIMEI', 'chimei'), ('Dreamstar', 'dreamstar'), ('SUNNY', 'sunny'), ('Navitech', 'navitech'), ('Hisense', 'hisense'), ('Skytech', 'skytech'), ('Hi-Level', 'hi-level'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Regal', 'vestel-regal'), ('DARFON', 'darfon'), ('-', ''), ('Panasonic', 'panasonic'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Homstar', 'homstar'), ('Next', 'next'), ('Acer', 'acer'), ('Dijitsu', 'dijitsu'), ('ONVO', 'onvo'), ('Osawa', 'osawa'), ('BOE', 'boe'), ('SUNNY-AXEN', 'sunny-axen'), ('Profilo', 'profilo'), ('Vestel-SEG', 'vestel-seg'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AWOX', 'awox'), ('AUO', 'auo'), ('YUMATU', 'yumatu'), ('GEEPAS', 'geepas'), ('ROWELL', 'rowell'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('MEGMEET', 'megmeet'), ('WOON', 'woon'), ('SAMSUNG', 'samsung'), ('NEXT', 'next'), ('LG', 'lg'), ('SEG', 'seg'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SHARP', 'sharp'), ('SONY', 'sony'), ('Vestel-ALBA', 'vestel-alba'), ('REGAL', 'regal'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Premier', 'premier'), ('Vestel', 'vestel'), ('PHILIPS', 'philips'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
