# Generated by Django 4.1.7 on 2023-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Vestel-Regal', 'vestel-regal'), ('CHIMEI', 'chimei'), ('Panasonic', 'panasonic'), ('WOON', 'woon'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SEG', 'seg'), ('DARFON', 'darfon'), ('Nordmende', 'nordmende'), ('MEGMEET', 'megmeet'), ('ONVO', 'onvo'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Dijitsu', 'dijitsu'), ('Premier', 'premier'), ('Vestel-SEG', 'vestel-seg'), ('SUNNY', 'sunny'), ('Dreamstar', 'dreamstar'), ('Hi-Level', 'hi-level'), ('-', ''), ('BOE', 'boe'), ('GEEPAS', 'geepas'), ('SUNNY-AXEN', 'sunny-axen'), ('Skytech', 'skytech'), ('SANYO', 'sanyo'), ('SAMSUNG', 'samsung'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Profilo', 'profilo'), ('Hisense', 'hisense'), ('Navitech', 'navitech'), ('Next', 'next'), ('Osawa', 'osawa'), ('ROWELL', 'rowell'), ('INNOLUX', 'innolux'), ('SONY', 'sony'), ('AUO', 'auo'), ('PHILIPS', 'philips'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('REGAL', 'regal'), ('Lifemaxx', 'lifemaxx'), ('Acer', 'acer'), ('LG', 'lg'), ('AWOX', 'awox'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Homstar', 'homstar'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-ALBA', 'vestel-alba'), ('NEXT', 'next'), ('SHARP', 'sharp'), ('YUMATU', 'yumatu'), ('AXEN', 'axen'), ('Vestel', 'vestel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED', 'led'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
