# Generated by Django 4.1.3 on 2022-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TCL', 'tcl'), ('Dreamstar', 'dreamstar'), ('GEEPAS', 'geepas'), ('Profilo', 'profilo'), ('AUO', 'auo'), ('Arçelik-Beko-Grundig', 'arcelik-beko-grundig'), ('Skytech', 'skytech'), ('ONVO', 'onvo'), ('Next', 'next'), ('SANYO', 'sanyo'), ('ROWELL', 'rowell'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('LG', 'lg'), ('AWOX', 'awox'), ('GRUNDIG', 'grundig'), ('ALTUS', 'altus'), ('TECHNOBOX', 'technobox'), ('BEKO', 'beko'), ('ARÇELİK', 'arcelik'), ('CVS', 'cvs'), ('-', ''), ('Dijitsu', 'dijitsu'), ('Botech', 'botech'), ('TELENOVA', 'telenova'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung'), ('PHILIPS', 'philips')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
