# Generated by Django 4.1.7 on 2023-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SANYO', 'sanyo'), ('SUNNY-AXEN', 'sunny-axen'), ('-', ''), ('AXEN', 'axen'), ('Osawa', 'osawa'), ('Acer', 'acer'), ('YUMATU', 'yumatu'), ('MEGMEET', 'megmeet'), ('SUNNY', 'sunny'), ('Skytech', 'skytech'), ('GEEPAS', 'geepas'), ('ONVO', 'onvo'), ('WOON', 'woon'), ('Vestel-ALBA', 'vestel-alba'), ('SAMSUNG', 'samsung'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Vestel', 'vestel'), ('Hi-Level', 'hi-level'), ('Lifemaxx', 'lifemaxx'), ('REGAL', 'regal'), ('Dijitsu', 'dijitsu'), ('AUO', 'auo'), ('SEG', 'seg'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AWOX', 'awox'), ('ROWELL', 'rowell'), ('Homstar', 'homstar'), ('Vestel-Regal', 'vestel-regal'), ('NEXT', 'next'), ('Dreamstar', 'dreamstar'), ('Premier', 'premier'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('LG', 'lg'), ('PHILIPS', 'philips'), ('DARFON', 'darfon'), ('CHIMEI', 'chimei'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Hisense', 'hisense'), ('SONY', 'sony'), ('Panasonic', 'panasonic'), ('Navitech', 'navitech'), ('Vestel-SEG', 'vestel-seg'), ('Next', 'next'), ('SHARP', 'sharp'), ('BOE', 'boe'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Nordmende', 'nordmende'), ('Profilo', 'profilo'), ('INNOLUX', 'innolux'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
