# Generated by Django 4.1.7 on 2023-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('SONY', 'sony'), ('SHARP', 'sharp'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Nordmende', 'nordmende'), ('Vestel-Regal', 'vestel-regal'), ('Navitech', 'navitech'), ('Hi-Level', 'hi-level'), ('SANYO', 'sanyo'), ('LG', 'lg'), ('Premier', 'premier'), ('Panasonic', 'panasonic'), ('Dreamstar', 'dreamstar'), ('Vestel-SEG', 'vestel-seg'), ('DARFON', 'darfon'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('MEGMEET', 'megmeet'), ('Acer', 'acer'), ('ROWELL', 'rowell'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AWOX', 'awox'), ('AUO', 'auo'), ('Lifemaxx', 'lifemaxx'), ('CHIMEI', 'chimei'), ('SUNNY', 'sunny'), ('NEXT', 'next'), ('Osawa', 'osawa'), ('Vestel', 'vestel'), ('ONVO', 'onvo'), ('SAMSUNG', 'samsung'), ('YUMATU', 'yumatu'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Dijitsu', 'dijitsu'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Skytech', 'skytech'), ('INNOLUX', 'innolux'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('BOE', 'boe'), ('Vestel-ALBA', 'vestel-alba'), ('WOON', 'woon'), ('-', ''), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AXEN', 'axen'), ('SEG', 'seg'), ('REGAL', 'regal'), ('Hisense', 'hisense'), ('Profilo', 'profilo'), ('GEEPAS', 'geepas'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Homstar', 'homstar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
