# Generated by Django 4.1.3 on 2022-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ROWELL', 'rowell'), ('AXEN', 'axen'), ('CVS', 'cvs'), ('-', ''), ('TECHNOBOX', 'technobox'), ('YUMATU', 'yumatu'), ('Skytech', 'skytech'), ('GEEPAS', 'geepas'), ('Botech', 'botech'), ('SUNNY-AXEN', 'sunny-axen'), ('PHILIPS', 'philips'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung'), ('Premier', 'premier'), ('SUNNY', 'sunny'), ('Next', 'next'), ('Profilo', 'profilo'), ('TCL', 'tcl'), ('NEXT', 'next'), ('AWOX', 'awox'), ('Homstar', 'homstar'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('SONY', 'sony'), ('TELENOVA', 'telenova'), ('LG', 'lg'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(),
        ),
    ]
