# Generated by Django 4.1.7 on 2023-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SAMSUNG', 'samsung'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SHARP', 'sharp'), ('Profilo', 'profilo'), ('Dreamstar', 'dreamstar'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('SONY', 'sony'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('BOE', 'boe'), ('RONAX-TELENOVA', 'ronax-telenova'), ('ONVO', 'onvo'), ('AXEN', 'axen'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-SEG', 'vestel-seg'), ('LG', 'lg'), ('Acer', 'acer'), ('Nordmende', 'nordmende'), ('-', ''), ('Vestel-ALBA', 'vestel-alba'), ('Panasonic', 'panasonic'), ('Skytech', 'skytech'), ('Lifemaxx', 'lifemaxx'), ('REGAL', 'regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('DARFON', 'darfon'), ('Premier', 'premier'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('GEEPAS', 'geepas'), ('YUMATU', 'yumatu'), ('SANYO', 'sanyo'), ('SUNNY', 'sunny'), ('WOON', 'woon'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Hisense', 'hisense'), ('Vestel', 'vestel'), ('Homstar', 'homstar'), ('ROWELL', 'rowell'), ('Hi-Level', 'hi-level'), ('AUO', 'auo'), ('Navitech', 'navitech'), ('INNOLUX', 'innolux'), ('SUNNY-AXEN', 'sunny-axen'), ('CHIMEI', 'chimei'), ('MEGMEET', 'megmeet'), ('Osawa', 'osawa'), ('SEG', 'seg'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
