# Generated by Django 4.1.3 on 2022-12-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_brand_alter_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Premier', 'premier'), ('Botech', 'botech'), ('ONVO', 'onvo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('LG', 'lg'), ('PHILIPS', 'philips'), ('ROWELL', 'rowell'), ('CVS', 'cvs'), ('Dreamstar', 'dreamstar'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('TCL', 'tcl'), ('VESTEL', 'vestel'), ('GEEPAS', 'geepas'), ('Profilo', 'profilo'), ('AXEN', 'axen'), ('NEXT', 'next'), ('-', ''), ('SUNNY-AXEN', 'sunny-axen'), ('Next', 'next'), ('TELENOVA', 'telenova'), ('SAMSUNG', 'samsung'), ('SONY', 'sony'), ('Homstar', 'homstar'), ('AWOX', 'awox'), ('SUNNY', 'sunny'), ('Dijitsu', 'dijitsu'), ('TECHNOBOX', 'technobox'), ('YUMATU', 'yumatu')], max_length=50, null=True),
        ),
    ]
