# Generated by Django 4.1.3 on 2022-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('NEXT', 'next'), ('Botech', 'botech'), ('GEEPAS', 'geepas'), ('Next', 'next'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('SANYO', 'sanyo'), ('VESTEL', 'vestel'), ('Premier', 'premier'), ('SONY', 'sony'), ('TCL', 'tcl'), ('SUNNY-AXEN', 'sunny-axen'), ('AWOX', 'awox'), ('TECHNOBOX', 'technobox'), ('LG', 'lg'), ('CVS', 'cvs'), ('Skytech', 'skytech'), ('-', ''), ('SAMSUNG', 'samsung'), ('Profilo', 'profilo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Dijitsu', 'dijitsu'), ('PHILIPS', 'philips'), ('YUMATU', 'yumatu'), ('TELENOVA', 'telenova'), ('AXEN', 'axen'), ('ROWELL', 'rowell'), ('SUNNY', 'sunny'), ('Homstar', 'homstar')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
