# Generated by Django 4.1.3 on 2022-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_brand_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('SUNNY-AXEN', 'sunny-axen'), ('TCL', 'tcl'), ('SONY', 'sony'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('Navitech', 'navitech'), ('AXEN', 'axen'), ('Botech', 'botech'), ('Dijitsu', 'dijitsu'), ('YUMATU', 'yumatu'), ('PHILIPS', 'philips'), ('Dreamstar', 'dreamstar'), ('SANYO', 'sanyo'), ('GEEPAS', 'geepas'), ('Homstar', 'homstar'), ('LG', 'lg'), ('Profilo', 'profilo'), ('CVS', 'cvs'), ('TECHNOBOX', 'technobox'), ('AWOX', 'awox'), ('-', ''), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung'), ('Premier', 'premier'), ('Next', 'next'), ('TELENOVA', 'telenova'), ('Skytech', 'skytech')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
