# Generated by Django 4.1.7 on 2023-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('GEEPAS', 'geepas'), ('SUNNY', 'sunny'), ('ONVO', 'onvo'), ('Premier', 'premier'), ('Vestel-SEG', 'vestel-seg'), ('AXEN', 'axen'), ('Dreamstar', 'dreamstar'), ('INNOLUX', 'innolux'), ('AWOX', 'awox'), ('REGAL', 'regal'), ('Navitech', 'navitech'), ('Acer', 'acer'), ('CHIMEI', 'chimei'), ('NEXT', 'next'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel-ALBA', 'vestel-alba'), ('-', ''), ('Osawa', 'osawa'), ('WOON', 'woon'), ('SEG', 'seg'), ('Skytech', 'skytech'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SONY', 'sony'), ('Profilo', 'profilo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SHARP', 'sharp'), ('Lifemaxx', 'lifemaxx'), ('Hi-Level', 'hi-level'), ('Nordmende', 'nordmende'), ('Homstar', 'homstar'), ('LG', 'lg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SUNNY-AXEN', 'sunny-axen'), ('AUO', 'auo'), ('Hisense', 'hisense'), ('BOE', 'boe'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Dijitsu', 'dijitsu'), ('YUMATU', 'yumatu'), ('DARFON', 'darfon'), ('Panasonic', 'panasonic'), ('MEGMEET', 'megmeet'), ('Next', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('PHILIPS', 'philips'), ('Vestel-Regal', 'vestel-regal'), ('SANYO', 'sanyo'), ('Vestel', 'vestel'), ('SAMSUNG', 'samsung'), ('ROWELL', 'rowell')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LED', 'led'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
