# Generated by Django 4.1.3 on 2022-12-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_theme_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Premier', 'premier'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Navitech', 'navitech'), ('Botech', 'botech'), ('TELENOVA', 'telenova'), ('LG', 'lg'), ('GEEPAS', 'geepas'), ('SAMSUNG', 'samsung'), ('Dijitsu', 'dijitsu'), ('VESTEL', 'vestel'), ('SONY', 'sony'), ('PHILIPS', 'philips'), ('ROWELL', 'rowell'), ('CVS', 'cvs'), ('AXEN', 'axen'), ('Next', 'next'), ('SUNNY-AXEN', 'sunny-axen'), ('TECHNOBOX', 'technobox'), ('-', ''), ('Homstar', 'homstar'), ('AWOX', 'awox'), ('Skytech', 'skytech'), ('Profilo', 'profilo'), ('YUMATU', 'yumatu'), ('SANYO', 'sanyo'), ('ONVO', 'onvo'), ('SUNNY', 'sunny'), ('Dreamstar', 'dreamstar'), ('TCL', 'tcl'), ('NEXT', 'next')], max_length=50, null=True),
        ),
    ]
