# Generated by Django 4.1.3 on 2022-12-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_theme_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TECHNOBOX', 'technobox'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung'), ('SUNNY', 'sunny'), ('TOSHIBA', 'toshiba'), ('AWOX', 'awox'), ('ROWELL', 'rowell'), ('Homstar', 'homstar'), ('NEXT', 'next'), ('GEEPAS', 'geepas'), ('SANYO', 'sanyo'), ('TCL', 'tcl'), ('Navitech', 'navitech'), ('AXEN', 'axen'), ('ONVO', 'onvo'), ('PHILIPS', 'philips'), ('Premier', 'premier'), ('LG', 'lg'), ('SUNNY-AXEN', 'sunny-axen'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Profilo', 'profilo'), ('-', ''), ('Panasonic', 'panasonic'), ('YUMATU', 'yumatu'), ('Dreamstar', 'dreamstar'), ('CVS', 'cvs'), ('TELENOVA', 'telenova'), ('Skytech', 'skytech'), ('Nordmende', 'nordmende'), ('Next', 'next'), ('Botech', 'botech'), ('Dijitsu', 'dijitsu'), ('SONY', 'sony')], max_length=50, null=True),
        ),
    ]
