# Generated by Django 4.1.7 on 2023-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('DARFON', 'darfon'), ('SUNNY-AXEN', 'sunny-axen'), ('INNOLUX', 'innolux'), ('SEG', 'seg'), ('Dreamstar', 'dreamstar'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('SUNNY', 'sunny'), ('AWOX', 'awox'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Dijitsu', 'dijitsu'), ('Osawa', 'osawa'), ('Vestel-SEG', 'vestel-seg'), ('AXEN', 'axen'), ('ONVO', 'onvo'), ('WOON', 'woon'), ('Skytech', 'skytech'), ('BOE', 'boe'), ('LG', 'lg'), ('NEXT', 'next'), ('Premier', 'premier'), ('MEGMEET', 'megmeet'), ('REGAL', 'regal'), ('PHILIPS', 'philips'), ('Homstar', 'homstar'), ('Panasonic', 'panasonic'), ('Next', 'next'), ('Navitech', 'navitech'), ('YUMATU', 'yumatu'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AUO', 'auo'), ('CHIMEI', 'chimei'), ('Vestel-Regal', 'vestel-regal'), ('SONY', 'sony'), ('-', ''), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel', 'vestel'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Profilo', 'profilo'), ('Hisense', 'hisense'), ('GEEPAS', 'geepas'), ('Lifemaxx', 'lifemaxx'), ('SHARP', 'sharp'), ('Acer', 'acer'), ('Nordmende', 'nordmende'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Vestel-ALBA', 'vestel-alba'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SAMSUNG', 'samsung'), ('ROWELL', 'rowell'), ('Hi-Level', 'hi-level'), ('SANYO', 'sanyo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED', 'led'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
