# Generated by Django 4.1.7 on 2023-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Navitech', 'navitech'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('YUMATU', 'yumatu'), ('SONY', 'sony'), ('ROWELL', 'rowell'), ('BOE', 'boe'), ('MEGMEET', 'megmeet'), ('INNOLUX', 'innolux'), ('Lifemaxx', 'lifemaxx'), ('AWOX', 'awox'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('AUO', 'auo'), ('Vestel-Regal', 'vestel-regal'), ('SANYO', 'sanyo'), ('SUNNY-AXEN', 'sunny-axen'), ('ONVO', 'onvo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Panasonic', 'panasonic'), ('CHIMEI', 'chimei'), ('Next', 'next'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('-', ''), ('SUNNY', 'sunny'), ('Nordmende', 'nordmende'), ('Profilo', 'profilo'), ('Vestel', 'vestel'), ('Osawa', 'osawa'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Dijitsu', 'dijitsu'), ('Skytech', 'skytech'), ('Homstar', 'homstar'), ('Vestel-SEG', 'vestel-seg'), ('REGAL', 'regal'), ('Premier', 'premier'), ('LG', 'lg'), ('PHILIPS', 'philips'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SAMSUNG', 'samsung'), ('AXEN', 'axen'), ('GEEPAS', 'geepas'), ('WOON', 'woon'), ('Vestel-ALBA', 'vestel-alba'), ('Hisense', 'hisense'), ('NEXT', 'next'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('DARFON', 'darfon'), ('Acer', 'acer'), ('SEG', 'seg'), ('SHARP', 'sharp'), ('Hi-Level', 'hi-level'), ('Dreamstar', 'dreamstar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
