# Generated by Django 4.1.7 on 2023-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SONY', 'sony'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('AUO', 'auo'), ('REGAL', 'regal'), ('-', ''), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel', 'vestel'), ('Nordmende', 'nordmende'), ('INNOLUX', 'innolux'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AWOX', 'awox'), ('Panasonic', 'panasonic'), ('BOE', 'boe'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-SEG', 'vestel-seg'), ('SEG', 'seg'), ('Profilo', 'profilo'), ('AXEN', 'axen'), ('GEEPAS', 'geepas'), ('SHARP', 'sharp'), ('ONVO', 'onvo'), ('Skytech', 'skytech'), ('ROWELL', 'rowell'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-ALBA', 'vestel-alba'), ('SANYO', 'sanyo'), ('Hi-Level', 'hi-level'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('SAMSUNG', 'samsung'), ('Homstar', 'homstar'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Acer', 'acer'), ('Dijitsu', 'dijitsu'), ('Lifemaxx', 'lifemaxx'), ('Dreamstar', 'dreamstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel-Regal', 'vestel-regal'), ('Next', 'next'), ('DARFON', 'darfon'), ('MEGMEET', 'megmeet'), ('Navitech', 'navitech'), ('Hisense', 'hisense'), ('CHIMEI', 'chimei'), ('Osawa', 'osawa'), ('Premier', 'premier'), ('RONAX-TELENOVA', 'ronax-telenova'), ('PHILIPS', 'philips'), ('WOON', 'woon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
