# Generated by Django 4.1.3 on 2022-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TELENOVA', 'telenova'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Nordmende', 'nordmende'), ('SONY', 'sony'), ('YUMATU', 'yumatu'), ('ROWELL', 'rowell'), ('TCL', 'tcl'), ('-', ''), ('VESTEL', 'vestel'), ('Navitech', 'navitech'), ('Premier', 'premier'), ('SAMSUNG', 'samsung'), ('Next', 'next'), ('TECHNOBOX', 'technobox'), ('PHILIPS', 'philips'), ('SUNNY', 'sunny'), ('SUNNY-AXEN', 'sunny-axen'), ('CVS', 'cvs'), ('Panasonic', 'panasonic'), ('NEXT', 'next'), ('SANYO', 'sanyo'), ('AXEN', 'axen'), ('ONVO', 'onvo'), ('GEEPAS', 'geepas'), ('AWOX', 'awox'), ('TOSHIBA', 'toshiba'), ('Profilo', 'profilo'), ('Dijitsu', 'dijitsu'), ('Botech', 'botech'), ('Skytech', 'skytech'), ('Dreamstar', 'dreamstar'), ('LG', 'lg'), ('Homstar', 'homstar')], max_length=50, null=True),
        ),
    ]
