# Generated by Django 4.1.3 on 2022-12-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ONVO', 'onvo'), ('-', ''), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Navitech', 'navitech'), ('LG', 'lg'), ('TOSHIBA', 'toshiba'), ('SUNNY', 'sunny'), ('YUMATU', 'yumatu'), ('PHILIPS', 'philips'), ('Next', 'next'), ('SANYO', 'sanyo'), ('CVS', 'cvs'), ('Dreamstar', 'dreamstar'), ('SONY', 'sony'), ('Premier', 'premier'), ('AXEN', 'axen'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('TCL', 'tcl'), ('Botech', 'botech'), ('TECHNOBOX', 'technobox'), ('Nordmende', 'nordmende'), ('TELENOVA', 'telenova'), ('Profilo', 'profilo'), ('Skytech', 'skytech'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung'), ('NEXT', 'next'), ('SUNNY-AXEN', 'sunny-axen'), ('GEEPAS', 'geepas'), ('Homstar', 'homstar'), ('ROWELL', 'rowell'), ('Panasonic', 'panasonic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
