# Generated by Django 4.1.7 on 2023-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Dijitsu', 'dijitsu'), ('BOE', 'boe'), ('Hisense', 'hisense'), ('Vestel-Regal', 'vestel-regal'), ('SHARP', 'sharp'), ('Osawa', 'osawa'), ('-', ''), ('REGAL', 'regal'), ('SUNNY-AXEN', 'sunny-axen'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Homstar', 'homstar'), ('Premier', 'premier'), ('AWOX', 'awox'), ('AXEN', 'axen'), ('NEXT', 'next'), ('Vestel-ALBA', 'vestel-alba'), ('YUMATU', 'yumatu'), ('Skytech', 'skytech'), ('Dreamstar', 'dreamstar'), ('SEG', 'seg'), ('Lifemaxx', 'lifemaxx'), ('Nordmende', 'nordmende'), ('SONY', 'sony'), ('Next', 'next'), ('Hi-Level', 'hi-level'), ('ONVO', 'onvo'), ('CHIMEI', 'chimei'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Panasonic', 'panasonic'), ('LG', 'lg'), ('INNOLUX', 'innolux'), ('Profilo', 'profilo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel', 'vestel'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('DARFON', 'darfon'), ('GEEPAS', 'geepas'), ('Vestel-SEG', 'vestel-seg'), ('Navitech', 'navitech'), ('WOON', 'woon'), ('AUO', 'auo'), ('Acer', 'acer'), ('SAMSUNG', 'samsung'), ('PHILIPS', 'philips'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SANYO', 'sanyo'), ('ROWELL', 'rowell'), ('MEGMEET', 'megmeet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('LED', 'led'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
