# Generated by Django 4.1.3 on 2022-12-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('CVS', 'cvs'), ('LG', 'lg'), ('GEEPAS', 'geepas'), ('AWOX', 'awox'), ('Navitech', 'navitech'), ('SONY', 'sony'), ('ONVO', 'onvo'), ('VESTEL', 'vestel'), ('NEXT', 'next'), ('Dreamstar', 'dreamstar'), ('SANYO', 'sanyo'), ('ROWELL', 'rowell'), ('SUNNY', 'sunny'), ('-', ''), ('Botech', 'botech'), ('Lifemaxx', 'lifemaxx'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Panasonic', 'panasonic'), ('PHILIPS', 'philips'), ('SAMSUNG', 'samsung'), ('AXEN', 'axen'), ('Dijitsu', 'dijitsu'), ('Nordmende', 'nordmende'), ('TOSHIBA', 'toshiba'), ('Osawa', 'osawa'), ('Homstar', 'homstar'), ('YUMATU', 'yumatu'), ('Premier', 'premier'), ('Skytech', 'skytech'), ('Profilo', 'profilo'), ('Next', 'next')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
