# Generated by Django 4.1.7 on 2023-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Dreamstar', 'dreamstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('ROWELL', 'rowell'), ('GEEPAS', 'geepas'), ('LG', 'lg'), ('Navitech', 'navitech'), ('Vestel-SEG', 'vestel-seg'), ('Next', 'next'), ('Vestel-ALBA', 'vestel-alba'), ('AXEN', 'axen'), ('BOE', 'boe'), ('Hisense', 'hisense'), ('Lifemaxx', 'lifemaxx'), ('INNOLUX', 'innolux'), ('Hi-Level', 'hi-level'), ('CHIMEI', 'chimei'), ('SUNNY', 'sunny'), ('SUNNY-AXEN', 'sunny-axen'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('AWOX', 'awox'), ('Premier', 'premier'), ('SEG', 'seg'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('NEXT', 'next'), ('WOON', 'woon'), ('Profilo', 'profilo'), ('-', ''), ('Nordmende', 'nordmende'), ('AUO', 'auo'), ('SHARP', 'sharp'), ('Panasonic', 'panasonic'), ('REGAL', 'regal'), ('SAMSUNG', 'samsung'), ('Osawa', 'osawa'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Homstar', 'homstar'), ('Vestel', 'vestel'), ('Vestel-Regal', 'vestel-regal'), ('YUMATU', 'yumatu'), ('DARFON', 'darfon'), ('Skytech', 'skytech'), ('Acer', 'acer'), ('MEGMEET', 'megmeet'), ('SONY', 'sony'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('ONVO', 'onvo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('PHILIPS', 'philips'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SANYO', 'sanyo'), ('Dijitsu', 'dijitsu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
