# Generated by Django 4.1.3 on 2022-12-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SONY', 'sony'), ('Skytech', 'skytech'), ('ROWELL', 'rowell'), ('NEXT', 'next'), ('Navitech', 'navitech'), ('Profilo', 'profilo'), ('Botech', 'botech'), ('SAMSUNG', 'samsung'), ('LG', 'lg'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('GEEPAS', 'geepas'), ('Nordmende', 'nordmende'), ('Osawa', 'osawa'), ('TOSHIBA', 'toshiba'), ('AWOX', 'awox'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('SUNNY-AXEN', 'sunny-axen'), ('Homstar', 'homstar'), ('VESTEL', 'vestel'), ('Dijitsu', 'dijitsu'), ('-', ''), ('YUMATU', 'yumatu'), ('PHILIPS', 'philips'), ('AXEN', 'axen'), ('Lifemaxx', 'lifemaxx'), ('Next', 'next'), ('CVS', 'cvs'), ('Panasonic', 'panasonic'), ('SANYO', 'sanyo'), ('Premier', 'premier'), ('SUNNY', 'sunny')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
