# Generated by Django 4.1.7 on 2023-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Homstar', 'homstar'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SAMSUNG', 'samsung'), ('Lifemaxx', 'lifemaxx'), ('Hi-Level', 'hi-level'), ('Navitech', 'navitech'), ('Dreamstar', 'dreamstar'), ('AXEN', 'axen'), ('SEG', 'seg'), ('SUNNY-AXEN', 'sunny-axen'), ('AUO', 'auo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('ROWELL', 'rowell'), ('Panasonic', 'panasonic'), ('MEGMEET', 'megmeet'), ('AWOX', 'awox'), ('BOE', 'boe'), ('Next', 'next'), ('CHIMEI', 'chimei'), ('ONVO', 'onvo'), ('Vestel', 'vestel'), ('SHARP', 'sharp'), ('SONY', 'sony'), ('Premier', 'premier'), ('Profilo', 'profilo'), ('INNOLUX', 'innolux'), ('Nordmende', 'nordmende'), ('DARFON', 'darfon'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel-ALBA', 'vestel-alba'), ('Osawa', 'osawa'), ('PHILIPS', 'philips'), ('Hisense', 'hisense'), ('Acer', 'acer'), ('WOON', 'woon'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('NEXT', 'next'), ('Dijitsu', 'dijitsu'), ('Skytech', 'skytech'), ('-', ''), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('Vestel-SEG', 'vestel-seg'), ('SANYO', 'sanyo'), ('Vestel-Regal', 'vestel-regal'), ('REGAL', 'regal'), ('GEEPAS', 'geepas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
