# Generated by Django 4.1.3 on 2023-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_brand_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yeni',
            field=models.CharField(blank=True, choices=[('Yeni', 'yeni')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ONVO', 'onvo'), ('Nordmende', 'nordmende'), ('SUNNY-AXEN', 'sunny-axen'), ('SAMSUNG', 'samsung'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Premier', 'premier'), ('LG', 'lg'), ('YUMATU', 'yumatu'), ('Dijitsu', 'dijitsu'), ('Osawa', 'osawa'), ('Navitech', 'navitech'), ('Skytech', 'skytech'), ('Dreamstar', 'dreamstar'), ('SONY', 'sony'), ('Profilo', 'profilo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Lifemaxx', 'lifemaxx'), ('GEEPAS', 'geepas'), ('Homstar', 'homstar'), ('AWOX', 'awox'), ('SANYO', 'sanyo'), ('AXEN', 'axen'), ('Botech', 'botech'), ('Panasonic', 'panasonic'), ('-', ''), ('VESTEL', 'vestel'), ('TOSHIBA', 'toshiba'), ('NEXT', 'next'), ('CVS', 'cvs'), ('SUNNY', 'sunny'), ('ROWELL', 'rowell')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
