# Generated by Django 4.1.3 on 2023-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_yeni_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Botech', 'botech'), ('Panasonic', 'panasonic'), ('Profilo', 'profilo'), ('ROWELL', 'rowell'), ('Dreamstar', 'dreamstar'), ('SUNNY', 'sunny'), ('Lifemaxx', 'lifemaxx'), ('TOSHIBA', 'toshiba'), ('SONY', 'sony'), ('Next', 'next'), ('PHILIPS', 'philips'), ('AXEN', 'axen'), ('SUNNY-AXEN', 'sunny-axen'), ('-', ''), ('CVS', 'cvs'), ('AWOX', 'awox'), ('VESTEL', 'vestel'), ('Homstar', 'homstar'), ('Premier', 'premier'), ('SAMSUNG', 'samsung'), ('Osawa', 'osawa'), ('Nordmende', 'nordmende'), ('LG', 'lg'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('GEEPAS', 'geepas'), ('ONVO', 'onvo'), ('Skytech', 'skytech'), ('Navitech', 'navitech'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo'), ('YUMATU', 'yumatu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
