# Generated by Django 4.1.7 on 2023-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Homstar', 'homstar'), ('BOE', 'boe'), ('MEGMEET', 'megmeet'), ('Acer', 'acer'), ('Vestel', 'vestel'), ('SUNNY', 'sunny'), ('-', ''), ('SONY', 'sony'), ('LG', 'lg'), ('ONVO', 'onvo'), ('Hi-Level', 'hi-level'), ('DARFON', 'darfon'), ('WOON', 'woon'), ('REGAL', 'regal'), ('INNOLUX', 'innolux'), ('ROWELL', 'rowell'), ('AWOX', 'awox'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Premier', 'premier'), ('Panasonic', 'panasonic'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('CHIMEI', 'chimei'), ('Nordmende', 'nordmende'), ('Lifemaxx', 'lifemaxx'), ('SEG', 'seg'), ('Hisense', 'hisense'), ('Osawa', 'osawa'), ('GEEPAS', 'geepas'), ('SAMSUNG', 'samsung'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dreamstar', 'dreamstar'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Dijitsu', 'dijitsu'), ('Vestel-ALBA', 'vestel-alba'), ('Navitech', 'navitech'), ('SHARP', 'sharp'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('NEXT', 'next'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AXEN', 'axen'), ('YUMATU', 'yumatu'), ('AUO', 'auo'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-Regal', 'vestel-regal'), ('Profilo', 'profilo'), ('Next', 'next'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('PHILIPS', 'philips')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('LED', 'led'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
