# Generated by Django 4.1.7 on 2023-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('GEEPAS', 'geepas'), ('Acer', 'acer'), ('ONVO', 'onvo'), ('AXEN', 'axen'), ('DARFON', 'darfon'), ('Osawa', 'osawa'), ('Hisense', 'hisense'), ('SUNNY-AXEN', 'sunny-axen'), ('REGAL', 'regal'), ('SAMSUNG', 'samsung'), ('SHARP', 'sharp'), ('SANYO', 'sanyo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dijitsu', 'dijitsu'), ('SONY', 'sony'), ('Skytech', 'skytech'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-SEG', 'vestel-seg'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Vestel-ALBA', 'vestel-alba'), ('Dreamstar', 'dreamstar'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel', 'vestel'), ('Profilo', 'profilo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SUNNY', 'sunny'), ('NEXT', 'next'), ('Panasonic', 'panasonic'), ('INNOLUX', 'innolux'), ('Vestel-Regal', 'vestel-regal'), ('SEG', 'seg'), ('CHIMEI', 'chimei'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('YUMATU', 'yumatu'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Premier', 'premier'), ('Lifemaxx', 'lifemaxx'), ('WOON', 'woon'), ('Homstar', 'homstar'), ('AUO', 'auo'), ('Navitech', 'navitech'), ('ROWELL', 'rowell'), ('-', ''), ('BOE', 'boe'), ('Hi-Level', 'hi-level'), ('MEGMEET', 'megmeet'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('AWOX', 'awox'), ('LG', 'lg'), ('Nordmende', 'nordmende')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED', 'led'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
