# Generated by Django 4.1.3 on 2023-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ROWELL', 'rowell'), ('Lifemaxx', 'lifemaxx'), ('Next', 'next'), ('AXEN', 'axen'), ('CVS', 'cvs'), ('Dreamstar', 'dreamstar'), ('SUNNY-AXEN', 'sunny-axen'), ('AWOX', 'awox'), ('ONVO', 'onvo'), ('LG', 'lg'), ('Osawa', 'osawa'), ('PHILIPS', 'philips'), ('SANYO', 'sanyo'), ('Homstar', 'homstar'), ('-', ''), ('GEEPAS', 'geepas'), ('YUMATU', 'yumatu'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Botech', 'botech'), ('Premier', 'premier'), ('Profilo', 'profilo'), ('TOSHIBA', 'toshiba'), ('Skytech', 'skytech'), ('SUNNY', 'sunny'), ('NEXT', 'next'), ('Navitech', 'navitech'), ('Nordmende', 'nordmende'), ('Dijitsu', 'dijitsu'), ('Panasonic', 'panasonic'), ('SONY', 'sony'), ('VESTEL', 'vestel'), ('SAMSUNG', 'samsung')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/products'),
        ),
    ]
