# Generated by Django 4.1.7 on 2023-02-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('AWOX', 'awox'), ('Dijitsu', 'dijitsu'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('REGAL', 'regal'), ('PHILIPS', 'philips'), ('Next', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Panasonic', 'panasonic'), ('ONVO', 'onvo'), ('INNOLUX', 'innolux'), ('SUNNY', 'sunny'), ('Vestel-Regal', 'vestel-regal'), ('Vestel', 'vestel'), ('YUMATU', 'yumatu'), ('Profilo', 'profilo'), ('NEXT', 'next'), ('Skytech', 'skytech'), ('Homstar', 'homstar'), ('Nordmende', 'nordmende'), ('SAMSUNG', 'samsung'), ('GEEPAS', 'geepas'), ('Hisense', 'hisense'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Lifemaxx', 'lifemaxx'), ('ROWELL', 'rowell'), ('DARFON', 'darfon'), ('Hi-Level', 'hi-level'), ('-', ''), ('SANYO', 'sanyo'), ('Vestel-SEG', 'vestel-seg'), ('Acer', 'acer'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SEG', 'seg'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Dreamstar', 'dreamstar'), ('SHARP', 'sharp'), ('MEGMEET', 'megmeet'), ('Vestel-ALBA', 'vestel-alba'), ('AUO', 'auo'), ('SONY', 'sony'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SUNNY-AXEN', 'sunny-axen'), ('LG', 'lg'), ('AXEN', 'axen'), ('BOE', 'boe'), ('CHIMEI', 'chimei'), ('Premier', 'premier'), ('Navitech', 'navitech'), ('Osawa', 'osawa'), ('WOON', 'woon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('LED', 'led'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
