# Generated by Django 4.1.3 on 2023-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_webp_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('-', ''), ('Osawa', 'osawa'), ('SEG', 'seg'), ('Botech', 'botech'), ('Dreamstar', 'dreamstar'), ('Navitech', 'navitech'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo'), ('Vestel-Toshiba', 'vestel-toshiba'), ('SAMSUNG', 'samsung'), ('ROWELL', 'rowell'), ('PHILIPS', 'philips'), ('Nordmende', 'nordmende'), ('ONVO', 'onvo'), ('AWOX', 'awox'), ('SONY', 'sony'), ('Profilo', 'profilo'), ('GEEPAS', 'geepas'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('RONAX', 'ronax'), ('SUNNY-AXEN', 'sunny-axen'), ('CVS', 'cvs'), ('Hisense', 'hisense'), ('LG', 'lg'), ('Skytech', 'skytech'), ('Homstar', 'homstar'), ('Hi-Level', 'hi-level'), ('YUMATU', 'yumatu'), ('NEXT', 'next'), ('WOON', 'woon'), ('Next', 'next'), ('BOE', 'boe'), ('Premier', 'premier'), ('ALBA', 'alba'), ('Panasonic', 'panasonic'), ('Lifemaxx', 'lifemaxx'), ('AXEN', 'axen')], max_length=50, null=True),
        ),
    ]
