# Generated by Django 4.1.7 on 2023-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Dreamstar', 'dreamstar'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SAMSUNG', 'samsung'), ('GEEPAS', 'geepas'), ('Vestel-ALBA', 'vestel-alba'), ('SHARP', 'sharp'), ('-', ''), ('Skytech', 'skytech'), ('SONY', 'sony'), ('DARFON', 'darfon'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Nordmende', 'nordmende'), ('ONVO', 'onvo'), ('SANYO', 'sanyo'), ('Osawa', 'osawa'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Next', 'next'), ('Hi-Level', 'hi-level'), ('ROWELL', 'rowell'), ('SEG', 'seg'), ('Acer', 'acer'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dijitsu', 'dijitsu'), ('WOON', 'woon'), ('CHIMEI', 'chimei'), ('REGAL', 'regal'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('BOE', 'boe'), ('Homstar', 'homstar'), ('Premier', 'premier'), ('AUO', 'auo'), ('Hisense', 'hisense'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel-SEG', 'vestel-seg'), ('Navitech', 'navitech'), ('MEGMEET', 'megmeet'), ('YUMATU', 'yumatu'), ('Lifemaxx', 'lifemaxx'), ('Vestel', 'vestel'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-Regal', 'vestel-regal'), ('Profilo', 'profilo'), ('LG', 'lg'), ('AWOX', 'awox'), ('INNOLUX', 'innolux'), ('AXEN', 'axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Panasonic', 'panasonic'), ('SUNNY-AXEN', 'sunny-axen'), ('PHILIPS', 'philips')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
