# Generated by Django 4.1.3 on 2023-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_views_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Homstar', 'homstar'), ('Skytech', 'skytech'), ('Botech', 'botech'), ('ALBA', 'alba'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo'), ('Dreamstar', 'dreamstar'), ('SUNNY', 'sunny'), ('Osawa', 'osawa'), ('PHILIPS', 'philips'), ('BOE', 'boe'), ('-', ''), ('ONVO', 'onvo'), ('Hi-Level', 'hi-level'), ('CVS', 'cvs'), ('RONAX', 'ronax'), ('ROWELL', 'rowell'), ('Premier', 'premier'), ('GEEPAS', 'geepas'), ('SUNNY-AXEN', 'sunny-axen'), ('Navitech', 'navitech'), ('SONY', 'sony'), ('Next', 'next'), ('LG', 'lg'), ('AWOX', 'awox'), ('Hisense', 'hisense'), ('Profilo', 'profilo'), ('Lifemaxx', 'lifemaxx'), ('AXEN', 'axen'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Nordmende', 'nordmende'), ('Panasonic', 'panasonic'), ('SEG', 'seg'), ('NEXT', 'next'), ('WOON', 'woon'), ('SAMSUNG', 'samsung'), ('Vestel-Toshiba', 'vestel-toshiba'), ('YUMATU', 'yumatu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
