# Generated by Django 4.1.7 on 2023-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('Skytech', 'skytech'), ('Premier', 'premier'), ('Hi-Level', 'hi-level'), ('LG', 'lg'), ('REGAL', 'regal'), ('-', ''), ('Vestel-ALBA', 'vestel-alba'), ('SUNNY', 'sunny'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Nordmende', 'nordmende'), ('Vestel-SEG', 'vestel-seg'), ('YUMATU', 'yumatu'), ('CHIMEI', 'chimei'), ('GEEPAS', 'geepas'), ('Dreamstar', 'dreamstar'), ('DARFON', 'darfon'), ('MEGMEET', 'megmeet'), ('PHILIPS', 'philips'), ('SAMSUNG', 'samsung'), ('Profilo', 'profilo'), ('NEXT', 'next'), ('SONY', 'sony'), ('Vestel', 'vestel'), ('SEG', 'seg'), ('ONVO', 'onvo'), ('BOE', 'boe'), ('ROWELL', 'rowell'), ('SANYO', 'sanyo'), ('Navitech', 'navitech'), ('Hisense', 'hisense'), ('INNOLUX', 'innolux'), ('WOON', 'woon'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SHARP', 'sharp'), ('Osawa', 'osawa'), ('Homstar', 'homstar'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AXEN', 'axen'), ('Panasonic', 'panasonic'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Acer', 'acer'), ('Lifemaxx', 'lifemaxx'), ('AUO', 'auo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Next', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED', 'led'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
