# Generated by Django 4.1.3 on 2023-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_views_product_views_count_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='benzerad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='benzerfiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='benzerstok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Premier', 'premier'), ('Hisense', 'hisense'), ('Skytech', 'skytech'), ('ONVO', 'onvo'), ('GEEPAS', 'geepas'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Dijitsu', 'dijitsu'), ('SUNNY-AXEN', 'sunny-axen'), ('Osawa', 'osawa'), ('YUMATU', 'yumatu'), ('Profilo', 'profilo'), ('Panasonic', 'panasonic'), ('AXEN', 'axen'), ('Vestel-Toshiba', 'vestel-toshiba'), ('Homstar', 'homstar'), ('WOON', 'woon'), ('Next', 'next'), ('SONY', 'sony'), ('-', ''), ('CVS', 'cvs'), ('SAMSUNG', 'samsung'), ('Navitech', 'navitech'), ('PHILIPS', 'philips'), ('ROWELL', 'rowell'), ('Dreamstar', 'dreamstar'), ('RONAX', 'ronax'), ('Nordmende', 'nordmende'), ('AWOX', 'awox'), ('LG', 'lg'), ('BOE', 'boe'), ('Lifemaxx', 'lifemaxx'), ('ALBA', 'alba'), ('SEG', 'seg'), ('NEXT', 'next'), ('Hi-Level', 'hi-level'), ('SUNNY', 'sunny'), ('SANYO', 'sanyo'), ('Botech', 'botech')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
