# Generated by Django 4.1.3 on 2023-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_productgallery_benzerad_productgallery_benzerfiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SEG', 'seg'), ('NEXT', 'next'), ('AWOX', 'awox'), ('GEEPAS', 'geepas'), ('ROWELL', 'rowell'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('ONVO', 'onvo'), ('WOON', 'woon'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-Toshiba', 'vestel-toshiba'), ('Skytech', 'skytech'), ('Lifemaxx', 'lifemaxx'), ('Premier', 'premier'), ('CVS', 'cvs'), ('SAMSUNG', 'samsung'), ('Next', 'next'), ('Dreamstar', 'dreamstar'), ('Osawa', 'osawa'), ('LG', 'lg'), ('SONY', 'sony'), ('PHILIPS', 'philips'), ('AXEN', 'axen'), ('Navitech', 'navitech'), ('Hi-Level', 'hi-level'), ('Panasonic', 'panasonic'), ('ALBA', 'alba'), ('Dijitsu', 'dijitsu'), ('-', ''), ('Nordmende', 'nordmende'), ('Homstar', 'homstar'), ('YUMATU', 'yumatu'), ('RONAX', 'ronax'), ('Profilo', 'profilo'), ('Hisense', 'hisense'), ('Botech', 'botech'), ('BOE', 'boe'), ('SUNNY', 'sunny'), ('SANYO', 'sanyo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
