# Generated by Django 4.1.7 on 2023-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('NEXT', 'next'), ('ONVO', 'onvo'), ('SEG', 'seg'), ('BOE', 'boe'), ('AXEN', 'axen'), ('Vestel-ALBA', 'vestel-alba'), ('MEGMEET', 'megmeet'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel-Regal', 'vestel-regal'), ('SHARP', 'sharp'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Lifemaxx', 'lifemaxx'), ('GEEPAS', 'geepas'), ('REGAL', 'regal'), ('Nordmende', 'nordmende'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('Vestel-SEG', 'vestel-seg'), ('PHILIPS', 'philips'), ('DARFON', 'darfon'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dijitsu', 'dijitsu'), ('CHIMEI', 'chimei'), ('Osawa', 'osawa'), ('Panasonic', 'panasonic'), ('Premier', 'premier'), ('SONY', 'sony'), ('Hisense', 'hisense'), ('Profilo', 'profilo'), ('Hi-Level', 'hi-level'), ('Homstar', 'homstar'), ('Dreamstar', 'dreamstar'), ('Skytech', 'skytech'), ('Next', 'next'), ('AUO', 'auo'), ('SAMSUNG', 'samsung'), ('WOON', 'woon'), ('INNOLUX', 'innolux'), ('Acer', 'acer'), ('-', ''), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('ROWELL', 'rowell'), ('Vestel', 'vestel'), ('SUNNY-AXEN', 'sunny-axen'), ('SUNNY', 'sunny'), ('SANYO', 'sanyo'), ('AWOX', 'awox'), ('Navitech', 'navitech'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED', 'led'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
