# Generated by Django 4.1.3 on 2023-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='benzerad',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='benzerfiyat',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='benzerstok',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('RONAX', 'ronax'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Dijitsu', 'dijitsu'), ('SONY', 'sony'), ('SUNNY', 'sunny'), ('Premier', 'premier'), ('Botech', 'botech'), ('CVS', 'cvs'), ('Lifemaxx', 'lifemaxx'), ('Homstar', 'homstar'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SAMSUNG', 'samsung'), ('GEEPAS', 'geepas'), ('LG', 'lg'), ('Vestel-Toshiba', 'vestel-toshiba'), ('ALBA', 'alba'), ('AWOX', 'awox'), ('SANYO', 'sanyo'), ('Navitech', 'navitech'), ('BOE', 'boe'), ('Dreamstar', 'dreamstar'), ('Osawa', 'osawa'), ('ROWELL', 'rowell'), ('Skytech', 'skytech'), ('YUMATU', 'yumatu'), ('WOON', 'woon'), ('Profilo', 'profilo'), ('NEXT', 'next'), ('-', ''), ('Panasonic', 'panasonic'), ('ONVO', 'onvo'), ('SEG', 'seg'), ('Hi-Level', 'hi-level'), ('AXEN', 'axen'), ('Hisense', 'hisense'), ('Nordmende', 'nordmende')], max_length=50, null=True),
        ),
    ]
