# Generated by Django 4.1.7 on 2023-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('LG', 'lg'), ('PHILIPS', 'philips'), ('SONY', 'sony'), ('SANYO', 'sanyo'), ('Nordmende', 'nordmende'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Navitech', 'navitech'), ('AWOX', 'awox'), ('REGAL', 'regal'), ('Profilo', 'profilo'), ('SUNNY', 'sunny'), ('Dijitsu', 'dijitsu'), ('Panasonic', 'panasonic'), ('Vestel-Regal', 'vestel-regal'), ('AXEN', 'axen'), ('Hi-Level', 'hi-level'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('CHIMEI', 'chimei'), ('AUO', 'auo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel', 'vestel'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('YUMATU', 'yumatu'), ('Next', 'next'), ('BOE', 'boe'), ('SUNNY-AXEN', 'sunny-axen'), ('SAMSUNG', 'samsung'), ('Lifemaxx', 'lifemaxx'), ('Vestel-SEG', 'vestel-seg'), ('WOON', 'woon'), ('Vestel-ALBA', 'vestel-alba'), ('Acer', 'acer'), ('-', ''), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Homstar', 'homstar'), ('Skytech', 'skytech'), ('ROWELL', 'rowell'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Hisense', 'hisense'), ('NEXT', 'next'), ('SEG', 'seg'), ('Premier', 'premier'), ('SHARP', 'sharp'), ('Dreamstar', 'dreamstar'), ('Osawa', 'osawa'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('INNOLUX', 'innolux'), ('ONVO', 'onvo'), ('MEGMEET', 'megmeet'), ('DARFON', 'darfon'), ('GEEPAS', 'geepas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
