# Generated by Django 4.1.7 on 2023-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ROWELL', 'rowell'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('LG', 'lg'), ('Nordmende', 'nordmende'), ('Skytech', 'skytech'), ('BOE', 'boe'), ('SUNNY', 'sunny'), ('MEGMEET', 'megmeet'), ('Profilo', 'profilo'), ('Vestel-Regal', 'vestel-regal'), ('DARFON', 'darfon'), ('INNOLUX', 'innolux'), ('YUMATU', 'yumatu'), ('SAMSUNG', 'samsung'), ('Premier', 'premier'), ('SANYO', 'sanyo'), ('AWOX', 'awox'), ('AUO', 'auo'), ('WOON', 'woon'), ('CHIMEI', 'chimei'), ('Navitech', 'navitech'), ('Acer', 'acer'), ('Hisense', 'hisense'), ('SONY', 'sony'), ('GEEPAS', 'geepas'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel', 'vestel'), ('Dijitsu', 'dijitsu'), ('Hi-Level', 'hi-level'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-ALBA', 'vestel-alba'), ('REGAL', 'regal'), ('SEG', 'seg'), ('Dreamstar', 'dreamstar'), ('Next', 'next'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('PHILIPS', 'philips'), ('Homstar', 'homstar'), ('AXEN', 'axen'), ('Vestel-SEG', 'vestel-seg'), ('Osawa', 'osawa'), ('SHARP', 'sharp'), ('Panasonic', 'panasonic'), ('-', ''), ('ONVO', 'onvo'), ('RONAX-TELENOVA', 'ronax-telenova')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('Plazma', 'plazma'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
