# Generated by Django 4.1.3 on 2023-01-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_product_brand_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_product',
            name='benzerresimlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('GEEPAS', 'geepas'), ('Dijitsu', 'dijitsu'), ('Premier', 'premier'), ('ONVO', 'onvo'), ('SUNNY', 'sunny'), ('Next', 'next'), ('Nordmende', 'nordmende'), ('ROWELL', 'rowell'), ('AXEN', 'axen'), ('Dreamstar', 'dreamstar'), ('NEXT', 'next'), ('CVS', 'cvs'), ('BOE', 'boe'), ('Lifemaxx', 'lifemaxx'), ('SUNNY-AXEN', 'sunny-axen'), ('ALBA', 'alba'), ('Profilo', 'profilo'), ('-', ''), ('Skytech', 'skytech'), ('RONAX', 'ronax'), ('WOON', 'woon'), ('Homstar', 'homstar'), ('Navitech', 'navitech'), ('Vestel-Toshiba', 'vestel-toshiba'), ('Panasonic', 'panasonic'), ('SAMSUNG', 'samsung'), ('Hi-Level', 'hi-level'), ('Hisense', 'hisense'), ('SANYO', 'sanyo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AWOX', 'awox'), ('Botech', 'botech'), ('PHILIPS', 'philips'), ('LG', 'lg'), ('SEG', 'seg'), ('SONY', 'sony'), ('Osawa', 'osawa'), ('YUMATU', 'yumatu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
