# Generated by Django 4.1.3 on 2023-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_related_product_benzerresimlink_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Nordmende', 'nordmende'), ('Profilo', 'profilo'), ('Navitech', 'navitech'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Homstar', 'homstar'), ('Panasonic', 'panasonic'), ('WOON', 'woon'), ('Next', 'next'), ('SAMSUNG', 'samsung'), ('Vestel-SEG', 'vestel-seg'), ('YUMATU', 'yumatu'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AXEN', 'axen'), ('SUNNY-AXEN', 'sunny-axen'), ('Dijitsu', 'dijitsu'), ('Vestel-ALBA', 'vestel-alba'), ('SUNNY', 'sunny'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('AUO', 'auo'), ('SONY', 'sony'), ('Hisense', 'hisense'), ('SANYO', 'sanyo'), ('BOE', 'boe'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('SEG', 'seg'), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('Dreamstar', 'dreamstar'), ('LG', 'lg'), ('Premier', 'premier'), ('AWOX', 'awox'), ('SHARP', 'sharp'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Vestel-Regal', 'vestel-regal'), ('RONAX', 'ronax'), ('PHILIPS', 'philips'), ('-', ''), ('ROWELL', 'rowell'), ('Osawa', 'osawa'), ('ONVO', 'onvo'), ('Skytech', 'skytech'), ('REGAL', 'regal'), ('Vestel', 'vestel'), ('Lifemaxx', 'lifemaxx')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
