# Generated by Django 4.1.7 on 2023-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-SEG', 'vestel-seg'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('SANYO', 'sanyo'), ('Navitech', 'navitech'), ('Premier', 'premier'), ('AWOX', 'awox'), ('Homstar', 'homstar'), ('SONY', 'sony'), ('AXEN', 'axen'), ('SUNNY', 'sunny'), ('SAMSUNG', 'samsung'), ('Lifemaxx', 'lifemaxx'), ('GEEPAS', 'geepas'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Dreamstar', 'dreamstar'), ('CHIMEI', 'chimei'), ('Skytech', 'skytech'), ('Vestel-ALBA', 'vestel-alba'), ('AUO', 'auo'), ('Vestel', 'vestel'), ('DARFON', 'darfon'), ('ONVO', 'onvo'), ('INNOLUX', 'innolux'), ('NEXT', 'next'), ('Next', 'next'), ('Hisense', 'hisense'), ('SHARP', 'sharp'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Hi-Level', 'hi-level'), ('BOE', 'boe'), ('MEGMEET', 'megmeet'), ('Dijitsu', 'dijitsu'), ('YUMATU', 'yumatu'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('WOON', 'woon'), ('SEG', 'seg'), ('Nordmende', 'nordmende'), ('Osawa', 'osawa'), ('LG', 'lg'), ('SUNNY-AXEN', 'sunny-axen'), ('ROWELL', 'rowell'), ('-', ''), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Acer', 'acer'), ('Profilo', 'profilo'), ('PHILIPS', 'philips'), ('Panasonic', 'panasonic'), ('REGAL', 'regal'), ('Vestel-Regal', 'vestel-regal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
