# Generated by Django 4.1.3 on 2023-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_product_brand_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_webp',
            field=models.ImageField(blank=True, upload_to='image_webp/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ONVO', 'onvo'), ('PHILIPS', 'philips'), ('Premier', 'premier'), ('Homstar', 'homstar'), ('Osawa', 'osawa'), ('SANYO', 'sanyo'), ('SONY', 'sony'), ('-', ''), ('Vestel-Regal', 'vestel-regal'), ('SEG', 'seg'), ('WOON', 'woon'), ('YUMATU', 'yumatu'), ('Navitech', 'navitech'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('REGAL', 'regal'), ('Hi-Level', 'hi-level'), ('Vestel-SEG', 'vestel-seg'), ('LG', 'lg'), ('Skytech', 'skytech'), ('AXEN', 'axen'), ('ROWELL', 'rowell'), ('NEXT', 'next'), ('Dijitsu', 'dijitsu'), ('SHARP', 'sharp'), ('Panasonic', 'panasonic'), ('Profilo', 'profilo'), ('GEEPAS', 'geepas'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Next', 'next'), ('Hisense', 'hisense'), ('Lifemaxx', 'lifemaxx'), ('AUO', 'auo'), ('Vestel', 'vestel'), ('SUNNY', 'sunny'), ('Dreamstar', 'dreamstar'), ('BOE', 'boe'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Nordmende', 'nordmende'), ('Vestel-ALBA', 'vestel-alba'), ('RONAX', 'ronax'), ('SUNNY-AXEN', 'sunny-axen'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AWOX', 'awox'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SAMSUNG', 'samsung')], max_length=100, null=True),
        ),
    ]
