# Generated by Django 4.1.7 on 2023-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SAMSUNG', 'samsung'), ('ROWELL', 'rowell'), ('Nordmende', 'nordmende'), ('SONY', 'sony'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Panasonic', 'panasonic'), ('Profilo', 'profilo'), ('Dijitsu', 'dijitsu'), ('SANYO', 'sanyo'), ('GEEPAS', 'geepas'), ('Osawa', 'osawa'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('NEXT', 'next'), ('Lifemaxx', 'lifemaxx'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Vestel', 'vestel'), ('REGAL', 'regal'), ('Premier', 'premier'), ('SUNNY', 'sunny'), ('LG', 'lg'), ('AXEN', 'axen'), ('Vestel-ALBA', 'vestel-alba'), ('-', ''), ('Skytech', 'skytech'), ('MEGMEET', 'megmeet'), ('Dreamstar', 'dreamstar'), ('DARFON', 'darfon'), ('YUMATU', 'yumatu'), ('Homstar', 'homstar'), ('Vestel-Regal', 'vestel-regal'), ('AWOX', 'awox'), ('SHARP', 'sharp'), ('BOE', 'boe'), ('INNOLUX', 'innolux'), ('SEG', 'seg'), ('SUNNY-AXEN', 'sunny-axen'), ('CHIMEI', 'chimei'), ('Navitech', 'navitech'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Hisense', 'hisense'), ('WOON', 'woon'), ('ONVO', 'onvo'), ('Acer', 'acer'), ('PHILIPS', 'philips'), ('Next', 'next'), ('Hi-Level', 'hi-level'), ('AUO', 'auo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
