# Generated by Django 4.1.3 on 2023-02-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_image_webp_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_webp',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ROWELL', 'rowell'), ('SUNNY-AXEN', 'sunny-axen'), ('SHARP', 'sharp'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel-ALBA', 'vestel-alba'), ('ONVO', 'onvo'), ('SONY', 'sony'), ('Nordmende', 'nordmende'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Profilo', 'profilo'), ('Vestel-SEG', 'vestel-seg'), ('SUNNY', 'sunny'), ('Skytech', 'skytech'), ('SEG', 'seg'), ('AUO', 'auo'), ('Vestel-Regal', 'vestel-regal'), ('Vestel', 'vestel'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('PHILIPS', 'philips'), ('Navitech', 'navitech'), ('YUMATU', 'yumatu'), ('Dreamstar', 'dreamstar'), ('Hisense', 'hisense'), ('REGAL', 'regal'), ('BOE', 'boe'), ('Premier', 'premier'), ('Osawa', 'osawa'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Hi-Level', 'hi-level'), ('SANYO', 'sanyo'), ('Dijitsu', 'dijitsu'), ('Next', 'next'), ('SAMSUNG', 'samsung'), ('-', ''), ('RONAX', 'ronax'), ('Panasonic', 'panasonic'), ('NEXT', 'next'), ('GEEPAS', 'geepas'), ('AXEN', 'axen'), ('LG', 'lg'), ('Lifemaxx', 'lifemaxx'), ('WOON', 'woon'), ('Homstar', 'homstar'), ('AWOX', 'awox')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
