# Generated by Django 4.1.7 on 2023-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Osawa', 'osawa'), ('SUNNY-AXEN', 'sunny-axen'), ('ROWELL', 'rowell'), ('AUO', 'auo'), ('Nordmende', 'nordmende'), ('YUMATU', 'yumatu'), ('Profilo', 'profilo'), ('SANYO', 'sanyo'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('GEEPAS', 'geepas'), ('ONVO', 'onvo'), ('DARFON', 'darfon'), ('RONAX-TELENOVA', 'ronax-telenova'), ('INNOLUX', 'innolux'), ('Dreamstar', 'dreamstar'), ('AWOX', 'awox'), ('AXEN', 'axen'), ('SHARP', 'sharp'), ('Vestel-ALBA', 'vestel-alba'), ('NEXT', 'next'), ('SAMSUNG', 'samsung'), ('Homstar', 'homstar'), ('SUNNY', 'sunny'), ('Vestel-SEG', 'vestel-seg'), ('Skytech', 'skytech'), ('Hi-Level', 'hi-level'), ('LG', 'lg'), ('Dijitsu', 'dijitsu'), ('REGAL', 'regal'), ('Next', 'next'), ('MEGMEET', 'megmeet'), ('PHILIPS', 'philips'), ('WOON', 'woon'), ('CHIMEI', 'chimei'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('-', ''), ('SEG', 'seg'), ('Hisense', 'hisense'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Regal', 'vestel-regal'), ('Acer', 'acer'), ('Vestel', 'vestel'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Navitech', 'navitech'), ('Premier', 'premier'), ('Panasonic', 'panasonic'), ('SONY', 'sony'), ('BOE', 'boe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
