# Generated by Django 4.1.3 on 2023-02-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_product_image_webp_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sontarih',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Lifemaxx', 'lifemaxx'), ('REGAL', 'regal'), ('-', ''), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Hi-Level', 'hi-level'), ('Premier', 'premier'), ('Navitech', 'navitech'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-ALBA', 'vestel-alba'), ('Vestel', 'vestel'), ('Homstar', 'homstar'), ('PHILIPS', 'philips'), ('Nordmende', 'nordmende'), ('SEG', 'seg'), ('AWOX', 'awox'), ('Next', 'next'), ('SONY', 'sony'), ('RONAX', 'ronax'), ('Vestel-SEG', 'vestel-seg'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo'), ('Osawa', 'osawa'), ('WOON', 'woon'), ('ONVO', 'onvo'), ('Dijitsu', 'dijitsu'), ('ROWELL', 'rowell'), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('AXEN', 'axen'), ('SHARP', 'sharp'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Profilo', 'profilo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('BOE', 'boe'), ('Hisense', 'hisense'), ('SUNNY-AXEN', 'sunny-axen'), ('GEEPAS', 'geepas'), ('Dreamstar', 'dreamstar'), ('Panasonic', 'panasonic'), ('Skytech', 'skytech'), ('AUO', 'auo'), ('SAMSUNG', 'samsung'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo')], max_length=100, null=True),
        ),
    ]
