# Generated by Django 4.1.7 on 2023-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SHARP', 'sharp'), ('Vestel', 'vestel'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Vestel-ALBA', 'vestel-alba'), ('ONVO', 'onvo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Dijitsu', 'dijitsu'), ('PHILIPS', 'philips'), ('Vestel-Regal', 'vestel-regal'), ('MEGMEET', 'megmeet'), ('SAMSUNG', 'samsung'), ('Premier', 'premier'), ('NEXT', 'next'), ('SUNNY', 'sunny'), ('SANYO', 'sanyo'), ('Acer', 'acer'), ('Osawa', 'osawa'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Panasonic', 'panasonic'), ('-', ''), ('Lifemaxx', 'lifemaxx'), ('Hisense', 'hisense'), ('Dreamstar', 'dreamstar'), ('INNOLUX', 'innolux'), ('YUMATU', 'yumatu'), ('RONAX-TELENOVA', 'ronax-telenova'), ('DARFON', 'darfon'), ('Homstar', 'homstar'), ('AXEN', 'axen'), ('Vestel-SEG', 'vestel-seg'), ('GEEPAS', 'geepas'), ('AUO', 'auo'), ('CHIMEI', 'chimei'), ('Next', 'next'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('WOON', 'woon'), ('Nordmende', 'nordmende'), ('SUNNY-AXEN', 'sunny-axen'), ('Profilo', 'profilo'), ('ROWELL', 'rowell'), ('SONY', 'sony'), ('Skytech', 'skytech'), ('Navitech', 'navitech'), ('LG', 'lg'), ('BOE', 'boe'), ('SEG', 'seg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('AWOX', 'awox'), ('Hi-Level', 'hi-level'), ('REGAL', 'regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
