# Generated by Django 4.1.3 on 2023-02-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_product_sontarih_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('LG', 'lg'), ('SEG', 'seg'), ('SONY', 'sony'), ('Premier', 'premier'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Navitech', 'navitech'), ('AWOX', 'awox'), ('ONVO', 'onvo'), ('Homstar', 'homstar'), ('SUNNY-AXEN', 'sunny-axen'), ('AXEN', 'axen'), ('RONAX', 'ronax'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Panasonic', 'panasonic'), ('Osawa', 'osawa'), ('-', ''), ('Hisense', 'hisense'), ('Dreamstar', 'dreamstar'), ('Skytech', 'skytech'), ('SAMSUNG', 'samsung'), ('SHARP', 'sharp'), ('Vestel-Regal', 'vestel-regal'), ('Vestel', 'vestel'), ('SANYO', 'sanyo'), ('AUO', 'auo'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('REGAL', 'regal'), ('GEEPAS', 'geepas'), ('Profilo', 'profilo'), ('PHILIPS', 'philips'), ('Vestel-SEG', 'vestel-seg'), ('Dijitsu', 'dijitsu'), ('Nordmende', 'nordmende'), ('ROWELL', 'rowell'), ('WOON', 'woon'), ('Next', 'next'), ('Hi-Level', 'hi-level'), ('NEXT', 'next'), ('Vestel-ALBA', 'vestel-alba'), ('YUMATU', 'yumatu'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Lifemaxx', 'lifemaxx'), ('BOE', 'boe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sontarih',
            field=models.DateTimeField(),
        ),
    ]
