# Generated by Django 4.1.3 on 2023-02-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Navitech', 'navitech'), ('PHILIPS', 'philips'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SAMSUNG', 'samsung'), ('AXEN', 'axen'), ('BOE', 'boe'), ('Dreamstar', 'dreamstar'), ('SUNNY', 'sunny'), ('SUNNY-AXEN', 'sunny-axen'), ('SHARP', 'sharp'), ('SONY', 'sony'), ('Osawa', 'osawa'), ('LG', 'lg'), ('Panasonic', 'panasonic'), ('SEG', 'seg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Skytech', 'skytech'), ('Vestel-Regal', 'vestel-regal'), ('SANYO', 'sanyo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Lifemaxx', 'lifemaxx'), ('Hisense', 'hisense'), ('AUO', 'auo'), ('GEEPAS', 'geepas'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Next', 'next'), ('Vestel-SEG', 'vestel-seg'), ('WOON', 'woon'), ('Profilo', 'profilo'), ('Premier', 'premier'), ('-', ''), ('Nordmende', 'nordmende'), ('Hi-Level', 'hi-level'), ('Homstar', 'homstar'), ('Dijitsu', 'dijitsu'), ('REGAL', 'regal'), ('AWOX', 'awox'), ('Vestel', 'vestel'), ('YUMATU', 'yumatu'), ('RONAX', 'ronax'), ('Vestel-ALBA', 'vestel-alba')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
