# Generated by Django 4.1.7 on 2023-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Hisense', 'hisense'), ('-', ''), ('Osawa', 'osawa'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AXEN', 'axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Next', 'next'), ('CHIMEI', 'chimei'), ('SEG', 'seg'), ('Nordmende', 'nordmende'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('REGAL', 'regal'), ('LG', 'lg'), ('YUMATU', 'yumatu'), ('Premier', 'premier'), ('ONVO', 'onvo'), ('Panasonic', 'panasonic'), ('Acer', 'acer'), ('NEXT', 'next'), ('AUO', 'auo'), ('Profilo', 'profilo'), ('Vestel-Regal', 'vestel-regal'), ('SAMSUNG', 'samsung'), ('MEGMEET', 'megmeet'), ('AWOX', 'awox'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Lifemaxx', 'lifemaxx'), ('Vestel-ALBA', 'vestel-alba'), ('Dreamstar', 'dreamstar'), ('BOE', 'boe'), ('SUNNY-AXEN', 'sunny-axen'), ('INNOLUX', 'innolux'), ('SHARP', 'sharp'), ('GEEPAS', 'geepas'), ('Dijitsu', 'dijitsu'), ('Navitech', 'navitech'), ('DARFON', 'darfon'), ('Vestel', 'vestel'), ('SANYO', 'sanyo'), ('ROWELL', 'rowell'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Hi-Level', 'hi-level'), ('Skytech', 'skytech'), ('SUNNY', 'sunny'), ('Vestel-SEG', 'vestel-seg'), ('WOON', 'woon'), ('SONY', 'sony'), ('Homstar', 'homstar'), ('PHILIPS', 'philips')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LCD', 'lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
