# Generated by Django 4.1.3 on 2023-02-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('RONAX', 'ronax'), ('Profilo', 'profilo'), ('Dijitsu', 'dijitsu'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AUO', 'auo'), ('YUMATU', 'yumatu'), ('Skytech', 'skytech'), ('LG', 'lg'), ('AWOX', 'awox'), ('WOON', 'woon'), ('Panasonic', 'panasonic'), ('Homstar', 'homstar'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AXEN', 'axen'), ('SONY', 'sony'), ('SEG', 'seg'), ('ROWELL', 'rowell'), ('PHILIPS', 'philips'), ('Navitech', 'navitech'), ('GEEPAS', 'geepas'), ('Lifemaxx', 'lifemaxx'), ('-', ''), ('Hi-Level', 'hi-level'), ('Osawa', 'osawa'), ('SUNNY', 'sunny'), ('ONVO', 'onvo'), ('Vestel-SEG', 'vestel-seg'), ('BOE', 'boe'), ('Vestel-Regal', 'vestel-regal'), ('REGAL', 'regal'), ('Next', 'next'), ('Hisense', 'hisense'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SHARP', 'sharp'), ('Vestel', 'vestel'), ('SUNNY-AXEN', 'sunny-axen'), ('Nordmende', 'nordmende'), ('Premier', 'premier'), ('Vestel-ALBA', 'vestel-alba'), ('SANYO', 'sanyo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Dreamstar', 'dreamstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('NEXT', 'next'), ('SAMSUNG', 'samsung')], max_length=100, null=True),
        ),
    ]
