# Generated by Django 4.1.3 on 2023-02-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Hi-Level', 'hi-level'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SEG', 'seg'), ('Vestel-Regal', 'vestel-regal'), ('Osawa', 'osawa'), ('Premier', 'premier'), ('BOE', 'boe'), ('NEXT', 'next'), ('Profilo', 'profilo'), ('AWOX', 'awox'), ('REGAL', 'regal'), ('Vestel-ALBA', 'vestel-alba'), ('YUMATU', 'yumatu'), ('SHARP', 'sharp'), ('Next', 'next'), ('LG', 'lg'), ('Homstar', 'homstar'), ('RONAX', 'ronax'), ('ONVO', 'onvo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SAMSUNG', 'samsung'), ('Panasonic', 'panasonic'), ('Skytech', 'skytech'), ('AXEN', 'axen'), ('Lifemaxx', 'lifemaxx'), ('Hisense', 'hisense'), ('WOON', 'woon'), ('SANYO', 'sanyo'), ('AUO', 'auo'), ('SUNNY', 'sunny'), ('Vestel-SEG', 'vestel-seg'), ('Navitech', 'navitech'), ('SONY', 'sony'), ('Dreamstar', 'dreamstar'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('PHILIPS', 'philips'), ('SUNNY-AXEN', 'sunny-axen'), ('GEEPAS', 'geepas'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel', 'vestel'), ('ROWELL', 'rowell'), ('-', ''), ('Dijitsu', 'dijitsu'), ('Nordmende', 'nordmende')], max_length=100, null=True),
        ),
    ]
