# Generated by Django 4.1.7 on 2023-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('-', ''), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Panasonic', 'panasonic'), ('Osawa', 'osawa'), ('Vestel-ALBA', 'vestel-alba'), ('SHARP', 'sharp'), ('INNOLUX', 'innolux'), ('Premier', 'premier'), ('MEGMEET', 'megmeet'), ('SEG', 'seg'), ('Homstar', 'homstar'), ('YUMATU', 'yumatu'), ('Navitech', 'navitech'), ('REGAL', 'regal'), ('Dreamstar', 'dreamstar'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('SONY', 'sony'), ('Acer', 'acer'), ('CHIMEI', 'chimei'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('BOE', 'boe'), ('DARFON', 'darfon'), ('Skytech', 'skytech'), ('Vestel', 'vestel'), ('AWOX', 'awox'), ('SUNNY', 'sunny'), ('Vestel-SEG', 'vestel-seg'), ('Nordmende', 'nordmende'), ('ONVO', 'onvo'), ('AUO', 'auo'), ('WOON', 'woon'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('RONAX-TELENOVA', 'ronax-telenova'), ('ROWELL', 'rowell'), ('NEXT', 'next'), ('Hisense', 'hisense'), ('AXEN', 'axen'), ('Profilo', 'profilo'), ('SAMSUNG', 'samsung'), ('GEEPAS', 'geepas'), ('Next', 'next'), ('Hi-Level', 'hi-level'), ('PHILIPS', 'philips'), ('SANYO', 'sanyo'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Dijitsu', 'dijitsu'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('LG', 'lg'), ('Vestel-Regal', 'vestel-regal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED', 'led'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
