# Generated by Django 4.1.7 on 2023-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_related_product_benzerstok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='photos3/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='webp3',
            field=models.ImageField(blank=True, null=True, upload_to='webp3/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('YUMATU', 'yumatu'), ('ROWELL', 'rowell'), ('Osawa', 'osawa'), ('MEGMEET', 'megmeet'), ('ONVO', 'onvo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AUO', 'auo'), ('SAMSUNG', 'samsung'), ('Profilo', 'profilo'), ('INNOLUX', 'innolux'), ('Hi-Level', 'hi-level'), ('SUNNY', 'sunny'), ('PHILIPS', 'philips'), ('WOON', 'woon'), ('SHARP', 'sharp'), ('Panasonic', 'panasonic'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('REGAL', 'regal'), ('DARFON', 'darfon'), ('GEEPAS', 'geepas'), ('NEXT', 'next'), ('Acer', 'acer'), ('AXEN', 'axen'), ('SONY', 'sony'), ('AWOX', 'awox'), ('SEG', 'seg'), ('Dijitsu', 'dijitsu'), ('Nordmende', 'nordmende'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Dreamstar', 'dreamstar'), ('Next', 'next'), ('Hisense', 'hisense'), ('BOE', 'boe'), ('Vestel-Regal', 'vestel-regal'), ('SANYO', 'sanyo'), ('Premier', 'premier'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Lifemaxx', 'lifemaxx'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('SUNNY-AXEN', 'sunny-axen'), ('CHIMEI', 'chimei'), ('Vestel-ALBA', 'vestel-alba'), ('Navitech', 'navitech'), ('-', ''), ('Vestel-SEG', 'vestel-seg'), ('Vestel', 'vestel'), ('LG', 'lg'), ('Homstar', 'homstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Skytech', 'skytech')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
