# Generated by Django 4.1.3 on 2023-02-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('WOON', 'woon'), ('SANYO', 'sanyo'), ('Osawa', 'osawa'), ('Vestel-Regal', 'vestel-regal'), ('Vestel', 'vestel'), ('BOE', 'boe'), ('SAMSUNG', 'samsung'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Dreamstar', 'dreamstar'), ('SONY', 'sony'), ('Hi-Level', 'hi-level'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Panasonic', 'panasonic'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AUO', 'auo'), ('GEEPAS', 'geepas'), ('RONAX', 'ronax'), ('PHILIPS', 'philips'), ('Premier', 'premier'), ('REGAL', 'regal'), ('Dijitsu', 'dijitsu'), ('AXEN', 'axen'), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('SUNNY', 'sunny'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('LG', 'lg'), ('Nordmende', 'nordmende'), ('Homstar', 'homstar'), ('-', ''), ('YUMATU', 'yumatu'), ('ONVO', 'onvo'), ('Vestel-ALBA', 'vestel-alba'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Lifemaxx', 'lifemaxx'), ('Vestel-SEG', 'vestel-seg'), ('ROWELL', 'rowell'), ('SEG', 'seg'), ('Profilo', 'profilo'), ('AWOX', 'awox'), ('SHARP', 'sharp'), ('Skytech', 'skytech'), ('NEXT', 'next'), ('Next', 'next'), ('Navitech', 'navitech')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
