# Generated by Django 4.1.3 on 2023-02-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Hisense', 'hisense'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('REGAL', 'regal'), ('SANYO', 'sanyo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel', 'vestel'), ('YUMATU', 'yumatu'), ('SUNNY-AXEN', 'sunny-axen'), ('Skytech', 'skytech'), ('SONY', 'sony'), ('RONAX', 'ronax'), ('Panasonic', 'panasonic'), ('NEXT', 'next'), ('LG', 'lg'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-ALBA', 'vestel-alba'), ('Navitech', 'navitech'), ('Dijitsu', 'dijitsu'), ('AXEN', 'axen'), ('WOON', 'woon'), ('ONVO', 'onvo'), ('Homstar', 'homstar'), ('BOE', 'boe'), ('Next', 'next'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Hi-Level', 'hi-level'), ('Profilo', 'profilo'), ('SHARP', 'sharp'), ('Osawa', 'osawa'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SEG', 'seg'), ('ROWELL', 'rowell'), ('SAMSUNG', 'samsung'), ('GEEPAS', 'geepas'), ('Dreamstar', 'dreamstar'), ('AWOX', 'awox'), ('-', ''), ('Lifemaxx', 'lifemaxx'), ('Vestel-Regal', 'vestel-regal'), ('SUNNY', 'sunny'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Nordmende', 'nordmende'), ('PHILIPS', 'philips'), ('Premier', 'premier'), ('AUO', 'auo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
