# Generated by Django 4.1.3 on 2023-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Vestel-SEG', 'vestel-seg'), ('Panasonic', 'panasonic'), ('Lifemaxx', 'lifemaxx'), ('SEG', 'seg'), ('SUNNY', 'sunny'), ('Hisense', 'hisense'), ('Vestel', 'vestel'), ('Profilo', 'profilo'), ('Dijitsu', 'dijitsu'), ('PHILIPS', 'philips'), ('YUMATU', 'yumatu'), ('Nordmende', 'nordmende'), ('SONY', 'sony'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('SHARP', 'sharp'), ('Osawa', 'osawa'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AUO', 'auo'), ('RONAX', 'ronax'), ('GEEPAS', 'geepas'), ('AWOX', 'awox'), ('ROWELL', 'rowell'), ('WOON', 'woon'), ('AXEN', 'axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Premier', 'premier'), ('Vestel-ALBA', 'vestel-alba'), ('Hi-Level', 'hi-level'), ('SAMSUNG', 'samsung'), ('BOE', 'boe'), ('Homstar', 'homstar'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('SUNNY-AXEN', 'sunny-axen'), ('NEXT', 'next'), ('ONVO', 'onvo'), ('Next', 'next'), ('Vestel-Regal', 'vestel-regal'), ('LG', 'lg'), ('Dreamstar', 'dreamstar'), ('REGAL', 'regal'), ('-', ''), ('Navitech', 'navitech'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sontarih',
            field=models.DateTimeField(blank=True),
        ),
    ]
