# Generated by Django 4.1.3 on 2023-02-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_product_brand_alter_product_sontarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('WOON', 'woon'), ('SEG', 'seg'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-SEG', 'vestel-seg'), ('AXEN', 'axen'), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('Premier', 'premier'), ('-', ''), ('Vestel-Regal', 'vestel-regal'), ('PHILIPS', 'philips'), ('Vestel', 'vestel'), ('SONY', 'sony'), ('REGAL', 'regal'), ('Navitech', 'navitech'), ('Nordmende', 'nordmende'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AUO', 'auo'), ('Next', 'next'), ('SUNNY', 'sunny'), ('Panasonic', 'panasonic'), ('Skytech', 'skytech'), ('Vestel-ALBA', 'vestel-alba'), ('Osawa', 'osawa'), ('ROWELL', 'rowell'), ('Homstar', 'homstar'), ('SANYO', 'sanyo'), ('Profilo', 'profilo'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('RONAX', 'ronax'), ('AWOX', 'awox'), ('ONVO', 'onvo'), ('Dijitsu', 'dijitsu'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Dreamstar', 'dreamstar'), ('NEXT', 'next'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('Hisense', 'hisense'), ('BOE', 'boe'), ('Lifemaxx', 'lifemaxx'), ('SHARP', 'sharp'), ('SAMSUNG', 'samsung'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sontarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
