# Generated by Django 4.1.3 on 2023-02-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, upload_to='photos2/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Premier', 'premier'), ('SANYO', 'sanyo'), ('Profilo', 'profilo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('LG', 'lg'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SUNNY-AXEN', 'sunny-axen'), ('SHARP', 'sharp'), ('Hisense', 'hisense'), ('Vestel-SEG', 'vestel-seg'), ('WOON', 'woon'), ('PHILIPS', 'philips'), ('Homstar', 'homstar'), ('SONY', 'sony'), ('Dreamstar', 'dreamstar'), ('Navitech', 'navitech'), ('Vestel-ALBA', 'vestel-alba'), ('Lifemaxx', 'lifemaxx'), ('ONVO', 'onvo'), ('REGAL', 'regal'), ('Osawa', 'osawa'), ('SEG', 'seg'), ('GEEPAS', 'geepas'), ('AXEN', 'axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SUNNY', 'sunny'), ('-', ''), ('Hi-Level', 'hi-level'), ('BOE', 'boe'), ('Next', 'next'), ('AUO', 'auo'), ('Nordmende', 'nordmende'), ('ROWELL', 'rowell'), ('SAMSUNG', 'samsung'), ('Panasonic', 'panasonic'), ('YUMATU', 'yumatu'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Skytech', 'skytech'), ('RONAX', 'ronax'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('NEXT', 'next'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('Vestel', 'vestel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
