# Generated by Django 4.1.3 on 2023-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='webp2',
            field=models.ImageField(blank=True, null=True, upload_to='webp2/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SUNNY-AXEN', 'sunny-axen'), ('YUMATU', 'yumatu'), ('Homstar', 'homstar'), ('Hisense', 'hisense'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Osawa', 'osawa'), ('Vestel-Regal', 'vestel-regal'), ('SONY', 'sony'), ('AWOX', 'awox'), ('PHILIPS', 'philips'), ('AUO', 'auo'), ('GEEPAS', 'geepas'), ('WOON', 'woon'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('-', ''), ('Skytech', 'skytech'), ('Hi-Level', 'hi-level'), ('REGAL', 'regal'), ('Vestel-SEG', 'vestel-seg'), ('Premier', 'premier'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Panasonic', 'panasonic'), ('LG', 'lg'), ('NEXT', 'next'), ('Vestel', 'vestel'), ('AXEN', 'axen'), ('BOE', 'boe'), ('ONVO', 'onvo'), ('Profilo', 'profilo'), ('Dreamstar', 'dreamstar'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Navitech', 'navitech'), ('SAMSUNG', 'samsung'), ('SANYO', 'sanyo'), ('RONAX', 'ronax'), ('Vestel-ALBA', 'vestel-alba'), ('SEG', 'seg'), ('Dijitsu', 'dijitsu'), ('SUNNY', 'sunny'), ('ROWELL', 'rowell'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Next', 'next'), ('SHARP', 'sharp'), ('Lifemaxx', 'lifemaxx'), ('Nordmende', 'nordmende')], max_length=100, null=True),
        ),
    ]
