# Generated by Django 4.1.3 on 2023-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_product_brand_delete_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('WOON', 'woon'), ('Dijitsu', 'dijitsu'), ('ROWELL', 'rowell'), ('Premier', 'premier'), ('RONAX', 'ronax'), ('Nordmende', 'nordmende'), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('Dreamstar', 'dreamstar'), ('Acer', 'acer'), ('SEG', 'seg'), ('NEXT', 'next'), ('Hi-Level', 'hi-level'), ('REGAL', 'regal'), ('Panasonic', 'panasonic'), ('Osawa', 'osawa'), ('Vestel', 'vestel'), ('YUMATU', 'yumatu'), ('LG', 'lg'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('ONVO', 'onvo'), ('AWOX', 'awox'), ('SONY', 'sony'), ('AXEN', 'axen'), ('SUNNY', 'sunny'), ('-', ''), ('AUO', 'auo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Navitech', 'navitech'), ('Lifemaxx', 'lifemaxx'), ('Profilo', 'profilo'), ('Vestel-SEG', 'vestel-seg'), ('BOE', 'boe'), ('GEEPAS', 'geepas'), ('Homstar', 'homstar'), ('SHARP', 'sharp'), ('SAMSUNG', 'samsung'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SANYO', 'sanyo'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Vestel-ALBA', 'vestel-alba'), ('Vestel-Regal', 'vestel-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Skytech', 'skytech')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='photos/products'),
        ),
    ]
