# Generated by Django 4.1.3 on 2023-02-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('YUMATU', 'yumatu'), ('PHILIPS', 'philips'), ('-', ''), ('Profilo', 'profilo'), ('SUNNY-AXEN', 'sunny-axen'), ('AXEN', 'axen'), ('Premier', 'premier'), ('Acer', 'acer'), ('RONAX', 'ronax'), ('AWOX', 'awox'), ('Vestel-Regal', 'vestel-regal'), ('ONVO', 'onvo'), ('BOE', 'boe'), ('SAMSUNG', 'samsung'), ('Osawa', 'osawa'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel', 'vestel'), ('Dijitsu', 'dijitsu'), ('Dreamstar', 'dreamstar'), ('Skytech', 'skytech'), ('Hisense', 'hisense'), ('Panasonic', 'panasonic'), ('Vestel-ALBA', 'vestel-alba'), ('Homstar', 'homstar'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AUO', 'auo'), ('SUNNY', 'sunny'), ('Navitech', 'navitech'), ('Next', 'next'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Lifemaxx', 'lifemaxx'), ('LG', 'lg'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Nordmende', 'nordmende'), ('ROWELL', 'rowell'), ('REGAL', 'regal'), ('SONY', 'sony'), ('Hi-Level', 'hi-level'), ('WOON', 'woon'), ('GEEPAS', 'geepas'), ('Vestel-SEG', 'vestel-seg'), ('SHARP', 'sharp'), ('NEXT', 'next'), ('SEG', 'seg'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
