# Generated by Django 4.1.3 on 2023-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Premier', 'premier'), ('Skytech', 'skytech'), ('SAMSUNG', 'samsung'), ('REGAL', 'regal'), ('SONY', 'sony'), ('WOON', 'woon'), ('Hi-Level', 'hi-level'), ('YUMATU', 'yumatu'), ('Osawa', 'osawa'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('SUNNY', 'sunny'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('-', ''), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('NEXT', 'next'), ('Lifemaxx', 'lifemaxx'), ('AUO', 'auo'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Homstar', 'homstar'), ('SEG', 'seg'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Panasonic', 'panasonic'), ('RONAX', 'ronax'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Profilo', 'profilo'), ('Vestel', 'vestel'), ('Navitech', 'navitech'), ('SANYO', 'sanyo'), ('ROWELL', 'rowell'), ('SHARP', 'sharp'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('LG', 'lg'), ('BOE', 'boe'), ('Nordmende', 'nordmende'), ('Vestel-ALBA', 'vestel-alba'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('PHILIPS', 'philips'), ('Next', 'next'), ('AXEN', 'axen'), ('GEEPAS', 'geepas'), ('Acer', 'acer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='photos/products'),
        ),
    ]
