# Generated by Django 4.1.3 on 2023-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_product_brand_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SHARP', 'sharp'), ('Osawa', 'osawa'), ('-', ''), ('GEEPAS', 'geepas'), ('ONVO', 'onvo'), ('Nordmende', 'nordmende'), ('Navitech', 'navitech'), ('Dreamstar', 'dreamstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Panasonic', 'panasonic'), ('Homstar', 'homstar'), ('AUO', 'auo'), ('LG', 'lg'), ('SONY', 'sony'), ('WOON', 'woon'), ('BOE', 'boe'), ('REGAL', 'regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Dijitsu', 'dijitsu'), ('Acer', 'acer'), ('SEG', 'seg'), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Regal', 'vestel-regal'), ('AXEN', 'axen'), ('SAMSUNG', 'samsung'), ('Next', 'next'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('Vestel', 'vestel'), ('PHILIPS', 'philips'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('RONAX', 'ronax'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('AWOX', 'awox'), ('Hi-Level', 'hi-level'), ('YUMATU', 'yumatu'), ('ROWELL', 'rowell'), ('Profilo', 'profilo'), ('Premier', 'premier'), ('NEXT', 'next'), ('Vestel-ALBA', 'vestel-alba')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
