# Generated by Django 4.1.3 on 2023-02-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_product_brand_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SEG', 'seg'), ('GEEPAS', 'geepas'), ('Profilo', 'profilo'), ('BOE', 'boe'), ('ONVO', 'onvo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Dreamstar', 'dreamstar'), ('Nordmende', 'nordmende'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Dijitsu', 'dijitsu'), ('Vestel', 'vestel'), ('Vestel-SEG', 'vestel-seg'), ('SAMSUNG', 'samsung'), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('Navitech', 'navitech'), ('YUMATU', 'yumatu'), ('AWOX', 'awox'), ('RONAX', 'ronax'), ('Homstar', 'homstar'), ('Osawa', 'osawa'), ('NEXT', 'next'), ('ROWELL', 'rowell'), ('Acer', 'acer'), ('REGAL', 'regal'), ('Panasonic', 'panasonic'), ('Hi-Level', 'hi-level'), ('Skytech', 'skytech'), ('SUNNY', 'sunny'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SHARP', 'sharp'), ('WOON', 'woon'), ('SANYO', 'sanyo'), ('Lifemaxx', 'lifemaxx'), ('PHILIPS', 'philips'), ('Vestel-ALBA', 'vestel-alba'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('LG', 'lg'), ('Next', 'next'), ('AXEN', 'axen'), ('Vestel-Regal', 'vestel-regal'), ('-', ''), ('AUO', 'auo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SONY', 'sony'), ('Premier', 'premier')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
