# Generated by Django 4.1.3 on 2023-02-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('BOE', 'boe'), ('Navitech', 'navitech'), ('YUMATU', 'yumatu'), ('Lifemaxx', 'lifemaxx'), ('ROWELL', 'rowell'), ('Dreamstar', 'dreamstar'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Nordmende', 'nordmende'), ('Panasonic', 'panasonic'), ('RONAX', 'ronax'), ('SAMSUNG', 'samsung'), ('PHILIPS', 'philips'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('NEXT', 'next'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AWOX', 'awox'), ('Acer', 'acer'), ('WOON', 'woon'), ('Profilo', 'profilo'), ('Homstar', 'homstar'), ('Vestel-ALBA', 'vestel-alba'), ('Vestel-Regal', 'vestel-regal'), ('Vestel', 'vestel'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('SONY', 'sony'), ('Premier', 'premier'), ('SUNNY-AXEN', 'sunny-axen'), ('Dijitsu', 'dijitsu'), ('LG', 'lg'), ('ONVO', 'onvo'), ('REGAL', 'regal'), ('SANYO', 'sanyo'), ('Skytech', 'skytech'), ('Next', 'next'), ('Vestel-SEG', 'vestel-seg'), ('Osawa', 'osawa'), ('SUNNY', 'sunny'), ('SEG', 'seg'), ('AXEN', 'axen'), ('Hisense', 'hisense'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('-', ''), ('SHARP', 'sharp'), ('AUO', 'auo')], max_length=100, null=True),
        ),
    ]
