# Generated by Django 4.1.3 on 2023-02-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('GEEPAS', 'geepas'), ('Next', 'next'), ('SONY', 'sony'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('SUNNY-AXEN', 'sunny-axen'), ('YUMATU', 'yumatu'), ('Hi-Level', 'hi-level'), ('SUNNY', 'sunny'), ('Homstar', 'homstar'), ('BOE', 'boe'), ('Vestel-SEG', 'vestel-seg'), ('Vestel-Regal', 'vestel-regal'), ('Hisense', 'hisense'), ('Vestel-ALBA', 'vestel-alba'), ('RONAX', 'ronax'), ('Dijitsu', 'dijitsu'), ('Skytech', 'skytech'), ('-', ''), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SEG', 'seg'), ('Acer', 'acer'), ('Profilo', 'profilo'), ('SHARP', 'sharp'), ('NEXT', 'next'), ('Lifemaxx', 'lifemaxx'), ('AXEN', 'axen'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('WOON', 'woon'), ('LG', 'lg'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('REGAL', 'regal'), ('Panasonic', 'panasonic'), ('SANYO', 'sanyo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Nordmende', 'nordmende'), ('AWOX', 'awox'), ('AUO', 'auo'), ('Osawa', 'osawa'), ('Premier', 'premier'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SAMSUNG', 'samsung'), ('Navitech', 'navitech'), ('PHILIPS', 'philips'), ('ROWELL', 'rowell'), ('Vestel', 'vestel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
