# Generated by Django 4.1.3 on 2023-02-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_product_brand_alter_product_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Lifemaxx', 'lifemaxx'), ('AUO', 'auo'), ('REGAL', 'regal'), ('Next', 'next'), ('RONAX', 'ronax'), ('NEXT', 'next'), ('WOON', 'woon'), ('Dijitsu', 'dijitsu'), ('Osawa', 'osawa'), ('SUNNY-AXEN', 'sunny-axen'), ('Nordmende', 'nordmende'), ('AXEN', 'axen'), ('PHILIPS', 'philips'), ('AWOX', 'awox'), ('Hisense', 'hisense'), ('Profilo', 'profilo'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SAMSUNG', 'samsung'), ('Dreamstar', 'dreamstar'), ('LG', 'lg'), ('Vestel-ALBA', 'vestel-alba'), ('YUMATU', 'yumatu'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Skytech', 'skytech'), ('Panasonic', 'panasonic'), ('Vestel-SEG', 'vestel-seg'), ('SEG', 'seg'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('ONVO', 'onvo'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SONY', 'sony'), ('SHARP', 'sharp'), ('BOE', 'boe'), ('Homstar', 'homstar'), ('-', ''), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('Premier', 'premier'), ('SUNNY', 'sunny'), ('Acer', 'acer'), ('Vestel-Regal', 'vestel-regal'), ('ROWELL', 'rowell'), ('Vestel', 'vestel'), ('Navitech', 'navitech')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50, null=True),
        ),
    ]
