# Generated by Django 4.1.3 on 2023-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('Plazma', 'plazma'), ('LCD', 'lcd')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('RONAX', 'ronax'), ('YUMATU', 'yumatu'), ('SEG', 'seg'), ('Lifemaxx', 'lifemaxx'), ('NEXT', 'next'), ('GEEPAS', 'geepas'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Hisense', 'hisense'), ('Homstar', 'homstar'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('CHIMEI', 'chimei'), ('PHILIPS', 'philips'), ('Navitech', 'navitech'), ('Skytech', 'skytech'), ('Panasonic', 'panasonic'), ('SONY', 'sony'), ('AXEN', 'axen'), ('INNOLUX', 'innolux'), ('Dijitsu', 'dijitsu'), ('-', ''), ('SHARP', 'sharp'), ('Profilo', 'profilo'), ('Vestel', 'vestel'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel-ALBA', 'vestel-alba'), ('ONVO', 'onvo'), ('LG', 'lg'), ('Hi-Level', 'hi-level'), ('SAMSUNG', 'samsung'), ('SUNNY', 'sunny'), ('Nordmende', 'nordmende'), ('Acer', 'acer'), ('Next', 'next'), ('ROWELL', 'rowell'), ('Osawa', 'osawa'), ('BOE', 'boe'), ('AWOX', 'awox'), ('Vestel-Regal', 'vestel-regal'), ('Dreamstar', 'dreamstar'), ('DARFON', 'darfon'), ('WOON', 'woon'), ('REGAL', 'regal'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo'), ('Premier', 'premier'), ('Vestel-SEG', 'vestel-seg'), ('AUO', 'auo'), ('SUNNY-AXEN', 'sunny-axen')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50, null=True),
        ),
    ]
